import {memo, useEffect, useMemo} from "react"

import {useSetAtom} from "jotai"
import {LOW_PRIORITY, useAtomValueWithSchedule} from "jotai-scheduler"

import {
    latestRevisionStatefulAtomFamily,
    requestLatestRevisionAtom,
} from "@/oss/state/entities/testset"

interface CommitMessageCellProps {
    testsetId: string
    maxLines?: number
}

/**
 * Custom cell component that displays the commit message for a testset row.
 *
 * Uses the testset ID to read from the latestRevisionStatefulAtomFamily which provides
 * the latest revision's commit message via batched fetching for performance.
 *
 * Features:
 * - Uses LOW_PRIORITY scheduling to defer updates during scroll (prevents jank)
 * - Leverages batched API requests (multiple cells mounting = single batch request)
 * - Shows loading state while fetching
 * - Memoized for optimal re-render performance
 * - Stable atom reference prevents unnecessary re-subscriptions
 */
const CommitMessageCell = memo(function CommitMessageCell({
    testsetId,
    maxLines = 2,
}: CommitMessageCellProps) {
    const requestLatestRevision = useSetAtom(requestLatestRevisionAtom)

    // Create a stable atom reference for this testset
    const statefulAtom = useMemo(() => latestRevisionStatefulAtomFamily(testsetId), [testsetId])

    // Use LOW_PRIORITY scheduling to prevent scroll jank
    const {data: latestRevision, isPending} = useAtomValueWithSchedule(statefulAtom, {
        priority: LOW_PRIORITY,
    })

    // Request the latest revision on mount (batched automatically)
    useEffect(() => {
        if (testsetId) {
            requestLatestRevision(testsetId)
        }
    }, [testsetId, requestLatestRevision])

    const message = latestRevision?.message

    // Filter out auto-generated commit messages
    const _isAutoGenerated = useMemo(() => {
        if (!message) return true
        return (
            message.startsWith("Updated testset:") ||
            message.startsWith("Patched testset") ||
            message.startsWith("Initial commit")
        )
    }, [message])

    // Show loading state while fetching
    if (isPending) {
        return <span className="text-xs text-muted-foreground animate-pulse">Loading...</span>
    }

    // Render the commit message with line-clamp ellipsis; title shows the full text.
    return (
        <p
            className="text-gray-600 !mb-0 overflow-hidden"
            style={{display: "-webkit-box", WebkitBoxOrient: "vertical", WebkitLineClamp: maxLines}}
            title={message ?? undefined}
        >
            {message}
        </p>
    )
})

CommitMessageCell.displayName = "CommitMessageCell"

export default CommitMessageCell
