apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenta-oss.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "agenta-oss.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "agenta-oss.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000