# Test values for Agenta OSS Helm chart
global:
  namespace: agenta-oss

externalUrls:
  api: "http://144.76.237.122/api"
  web: "http://144.76.237.122"
  services: "http://144.76.237.122/services"

# Override Agenta application images to use ghcr.io
images:
  web:
    repository: ghcr.io/agenta-ai/agenta-web
    tag: latest
    pullPolicy: IfNotPresent
  api: 
    repository: ghcr.io/agenta-ai/agenta-api
    tag: latest
    pullPolicy: IfNotPresent
  chat:
    repository: ghcr.io/agenta-ai/agenta-chat
    tag: latest
    pullPolicy: IfNotPresent
  completion:
    repository: ghcr.io/agenta-ai/agenta-completion
    tag: latest
    pullPolicy: IfNotPresent

# Enable all infrastructure with minimal persistence for testing
postgresql:
  enabled: true
  auth:
    postgresPassword: "password"
    username: "username"
    password: "password"
    database: "agenta_oss_core"
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "16"
  primary:
    persistence:
      enabled: false  # Disable for testing
    initdb:
      scripts:
        init-db.sql: |
          CREATE DATABASE agenta_oss_tracing;
          CREATE DATABASE agenta_oss_supertokens;

redis:
  enabled: true
  auth:
    enabled: false
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: "7.2"
  master:
    persistence:
      enabled: false  # Disable for testing

rabbitmq:
  enabled: true
  auth:
    username: "guest"
    password: "guest"
  image:
    registry: docker.io
    repository: bitnami/rabbitmq
    tag: "3.13"
  persistence:
    enabled: false  # Disable for testing

supertokens:
  enabled: true

# Enable ingress now that we have a clean environment
ingress:
  enabled: true
  className: "nginx"
  host: ""  # IP-based access
  annotations: {}
  tls:
    enabled: false