log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "web-secure"
          scheme: "https"

  web-secure:
    address: ":443"

certificatesResolvers:
  myResolver:
    acme:
      tlschallenge: true
      email: "youremailaddress@prodivder.com"
      storage: "acme.json"
      httpChallenge: # Using HTTP challenge for non-standard HTTPS port
        entryPoint: "web" # Validates domain ownership via port 80

providers:
  docker: {}
