@host = http://localhost
@token = replace-me
@base_url = {{host}}/api/v2/tracing

###
# @name create_account
POST {{host}}/api/admin/account
Content-Type: application/json
Authorization: Access {{token}}

###
@user_id = {{create_account.response.body.user.id}}
@authorization = {{create_account.response.body.scopes[0].credentials}}

###
POST {{base_url}}/spans/
Content-Type: application/json
Authorization: {{authorization}}

{
  "spans": [
    { "trace_id": "20000000000000000000000000000000", "span_id": "2000000000000000", "end_time": "2025-04-20T10:00:00+00:00" },
    { "trace_id": "20000000000000000000000000000000", "span_id": "2000000000000001", "end_time": "2025-04-20T11:00:00+00:00" },
    { "trace_id": "20000000000000000000000000000000", "span_id": "2000000000000002", "end_time": "2025-04-20T12:00:00+00:00" }
  ]
}

###
# test: filter by end_time = 2025-04-20T10:00:00+00:00 (IMPLICIT IS)
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "value": "2025-04-20T10:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time = 1745143200
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "value": 1745143200 }
    ]
  }
}

###
# test: filter by end_time IS 2025-04-20T10:00:00+00:00
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "is", "value": "2025-04-20T10:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time IS_NOT 2025-04-20T10:00:00+00:00
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "is_not", "value": "2025-04-20T10:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time EQ 2025-04-20T11:00:00+00:00
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "eq", "value": "2025-04-20T11:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time NEQ 2025-04-20T11:00:00+00:00
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "neq", "value": "2025-04-20T11:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time GT 2025-04-20T10:00:00+00:00
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "gt", "value": "2025-04-20T10:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time LT 2025-04-20T12:00:00+00:00
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "lt", "value": "2025-04-20T12:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time GTE 2025-04-20T11:00:00+00:00
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "gte", "value": "2025-04-20T11:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time LTE 2025-04-20T11:00:00+00:00
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "lte", "value": "2025-04-20T11:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time BETWEEN [2025-04-20T10:00:00+00:00, 2025-04-20T11:00:00+00:00]
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "btwn", "value": ["2025-04-20T10:00:00+00:00", "2025-04-20T11:00:00+00:00"] }
    ]
  }
}

###
# test: filter by end_time STARTSWITH [...]
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "startswith", "value": "2025-04-20 10" }
    ]
  }
}

###
# test: filter by end_time ENDSWITH [...]
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "endswith", "value": "10:00:00+00" }
    ]
  }
}

###
# test: filter by end_time CONTAINS [...]
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "contains", "value": "11:00" }
    ]
  }
}

###
# test: filter by end_time MATCHES [...]
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "matches", "value": "04-20 12" }
    ]
  }
}

###
# test: filter by end_time LIKE [...]
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "like", "value": "%11:00%" }
    ]
  }
}

###
# test: filter by end_time IN [...]
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "in", "value": ["2025-04-20T10:00:00+00:00", "2025-04-20T12:00:00+00:00"] }
    ]
  }
}

###
# test: filter by end_time NOT_IN [2025-04-20T10:00:00+00:00, 2025-04-20T12:00:00+00:00]
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "not_in", "value": ["2025-04-20T10:00:00+00:00", "2025-04-20T12:00:00+00:00"] }
    ]
  }
}

###
# test: filter by end_time HAS [...] -- unsupported
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "has", "value": "2025-04-20T10:00:00+00:00" }
    ]
  }
}

###
# test: filter by end_time HAS_NOT [...] -- unsupported
POST {{base_url}}/spans/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "filter": {
    "conditions": [
      { "field": "end_time", "operator": "has_not", "value": "2025-04-20T10:00:00+00:00" }
    ]
  }
}