{{- if eq (include "agenta.api.enabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenta.fullname" . }}-api
  labels:
    {{- include "agenta.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ include "agenta.api.port" . }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agenta.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
