@host = http://localhost
@token = change-me
@base_url = {{host}}/api/preview/evaluations

###
# @name create_account
POST {{host}}/api/admin/account
Content-Type: application/json
Authorization: Access {{token}}

###
@user_id = {{create_account.response.body.user.id}}
@authorization = {{create_account.response.body.scopes[0].credentials}}

### - RUNS ---------------------------------------------------------------------

### 1.1. REQUEST: Create run(s)
# @name create_runs
POST {{base_url}}/runs/
Content-Type: application/json
Authorization: {{authorization}}

{
  "runs": [
    {
      "key": "demo-evaluation",
      "name": "Demo run",
      "description": "run to test basic creation",
      "meta": {
        "my-meta": "aloha"
      },
      "data": {
        "results": [
          {
            "key": "some-testset",
            "type": "input",
            "origin": "custom",
            "references": {
              "testset": {
                "id": "4448964e-dc0d-41ec-a855-46773decad01"
              },
              "testset_variant": {
                "id": "80b80599-737e-4454-a01f-96151b077040"
              },
              "testset_revision": {
                "id": "08a8084c-96d8-4642-a695-8b2537d24211"
              }
            }
          },
          {
            "key": "some-application",
            "type": "invocation",
            "origin": "custom",
            "references": {
              "application": {
                "id": "c9d5e07c-2324-4b63-85a5-b83fa1a1f2ba"
              },
              "application_variant": {
                "id": "c96ca14e-5eda-4390-a659-2f5425d07a31"
              },
              "application_revision": {
                "id": "3b98bd3c-ed4c-4114-91da-20ade9958ab9"
              }
            },
            "inputs": [
              { "key": "some-testset" }
            ]
          },
          {
            "key": "some-evaluator",
            "type": "annotation",
            "origin": "custom",
            "references": {
              "evaluator": {
                "id": "2037d384-f201-455f-b890-b6be8fdb017c"
              },
              "evaluator_variant": {
                "id": "79b34629-7836-4bce-a1ee-fa4d80e7c7e0"
              },
              "evaluator_revision": {
                "id": "24840975-d42f-451a-8a9a-2596e4bb54df"
              }
            },
            "inputs": [
              { "key": "some-testset" },
              { "key": "some-application" }
            ]
          }
        ],
        "mappings": [
          {
            "column":{
              "kind": "input",
              "name": "Country"
            },
            "step": {
              "key": "some-testset",
              "path": "country"
            }
          },
          {
            "column": {
              "kind": "input",
              "name": "Capital (expected)"
            },
            "step": {
              "key": "some-testset",
              "path": "correct_answer"
            }
          },
          {
            "column": {
              "kind": "application",
              "name": "Capital (actual)"
            },
            "step": {
              "key": "some-application",
              "path": "data.outputs.answer"
            }
          },
          {
            "column": {
              "kind": "evaluator",
              "name": "Score"
            },
            "step": {
              "key": "some-application",
              "path": "data.outputs.score"
            }
          },
          {
            "column": {
              "kind": "evaluator",
              "name": "Confidence"
            },
            "step": {
              "key": "some-application",
              "path": "data.outputs.confidence"
            }
          },
          {
            "column": {
              "kind": "evaluator",
              "name": "Explanation"
            },
            "step": {
              "key": "some-application",
              "path": "data.outputs.explanation"
            }
          }
        ]
      }
    }
  ]
}

###
@run_id = {{create_runs.response.body.runs[0].id}}

### 1.2. REQUEST: Close run
POST {{base_url}}/runs/{{run_id}}/close
Content-Type: application/json
Authorization: {{authorization}}

### 1.3. REQUEST: Open run
POST {{base_url}}/runs/{{run_id}}/open
Content-Type: application/json
Authorization: {{authorization}}

### 1.4. REQUEST: Get run
GET {{base_url}}/runs/{{run_id}}
Content-Type: application/json
Authorization: {{authorization}}

### - SCENARIOS ----------------------------------------------------------------

### 2.1. REQUEST: Create scenarios
# @name create_scenarios
POST {{base_url}}/scenarios/
Content-Type: application/json
Authorization: {{authorization}}

{
  "scenarios": [
    {
      "run_id": "{{run_id}}"
    },
    {
      "run_id": "{{run_id}}"
    }
  ]
}

###
@scenario_id_1 = {{create_scenarios.response.body.scenarios[0].id}}
@scenario_id_2 = {{create_scenarios.response.body.scenarios[1].id}}

### 2.1.1. REQUEST: Get all scenarios by run_id
# @name get_scenarios
POST {{base_url}}/scenarios/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "scenario": {
    "run_id": "{{run_id}}"
  }
}

### 2.1.2. REQUEST: Get scenarios by run_id with windowing
# @name get_scenarios
POST {{base_url}}/scenarios/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "scenario": {
    "run_id": "{{run_id}}"
  },
  "windowing": {
    "limit": 2
  }
}

###
@next_scenario = {{get_scenarios.response.body.scenarios[1].id}}

### 2.1.3. REQUEST: Get scenarios by run_id with windowing
# @name get_scenarios
POST {{base_url}}/scenarios/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "scenario": {
    "run_id": "{{run_id}}"
  },
  "windowing": {
    "limit": 2,
    "next": "{{next_scenario}}"
  }
}

### - RESULTS ------------------------------------------------------------------

### 3.1.1 REQUEST: Create input steps for scenarios 1 and 2
# @name create_results
POST {{base_url}}/results/
Content-Type: application/json
Authorization: {{authorization}}

{
  "results": [
    {
      "status": "success",
      "step_key": "some-testset",
      "testcase_id": "5619b65c-8639-40c8-be68-c8b661f22dbe",
      "scenario_id": "{{scenario_id_1}}",
      "run_id": "{{run_id}}"
    },
    {
      "status": "success",
      "step_key": "some-testest",
      "testcase_id": "1b3c9a82-c97b-44ec-a77d-73c754069c70",
      "scenario_id": "{{scenario_id_2}}",
      "run_id": "{{run_id}}"
    }
  ]
}

### 3.1.2 REQUEST: Create invocation step for scenario 1
POST {{base_url}}/results/
Content-Type: application/json
Authorization: {{authorization}}

{
  "results": [
    {
      "status": "success",
      "step_key": "some-application",
      "trace_id": "b84f3862c7b74e759e19eeee88b5a1ba",
      "scenario_id": "{{scenario_id_1}}",
      "run_id": "{{run_id}}"
    }
  ]
}

### 3.1.3 REQUEST: Create annotation step for scenario 1
POST {{base_url}}/results/
Content-Type: application/json
Authorization: {{authorization}}

{
  "results": [
    {
      "status": "success",
      "step_key": "some-evaluator",
      "trace_id": "306eb5ccd299493bb651985dff3ad9a7",
      "scenario_id": "{{scenario_id_1}}",
      "run_id": "{{run_id}}"
    }
  ]
}

### 3.1.4 REQUEST: Create invocation step for scenario 2
POST {{base_url}}/results/
Content-Type: application/json
Authorization: {{authorization}}

{
  "results": [
    {
      "status": "success",
      "step_key": "some-application",
      "trace_id": "0773c47f216349ed8e5617830ae436ce",
      "scenario_id": "{{scenario_id_2}}",
      "run_id": "{{run_id}}"
    }
  ]
}

### 3.1.5 REQUEST: Create annotation step for scenario 2
POST {{base_url}}/results/
Content-Type: application/json
Authorization: {{authorization}}

{
  "results": [
    {
      "status": "success",
      "step_key": "some-evaluator",
      "trace_id": "09989c5181784174ad44dd19da5b4f67",
      "scenario_id": "{{scenario_id_2}}",
      "run_id": "{{run_id}}"
    }
  ]
}

### 3.2.1 REQUEST: Get all steps by run_id
# @name get_all_steps
POST {{base_url}}/results/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "result": {
    "run_id": "{{run_id}}"
  }
}

###

### 3.2.2 REQUEST: Get all steps by run_id with windowing
# @name get_steps
POST {{base_url}}/results/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "result": {
    "run_id": "{{run_id}}"
  },
  "windowing": {
    "limit": 2
  }
}

###
@next_result = {{get_steps.response.body.results[1].id}}


### 3.2.3 REQUEST: Get all steps by run_id with windowing
# @name get_steps
POST {{base_url}}/results/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "result": {
    "run_id": "{{run_id}}"
  },
  "windowing": {
    "limit": 2,
    "next": "{{next_result}}"
  }
}

### 3.3.1 REQUEST: Get all steps by run_id and key
POST {{base_url}}/results/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "result": {
    "run_id": "{{run_id}}",
    "step_keys": ["some-application", "some-evaluator"]
  }
}

### 3.3.2 REQUEST: Get all steps by run_id and status
POST {{base_url}}/results/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "result": {
    "run_id": "{{run_id}}",
    "statuses": ["pending", "success"]
  }
}

### 3.3.3 REQUEST: Get all steps by run_id and scenario_id
POST {{base_url}}/results/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "result": {
    "run_id": "{{run_id}}",
    "scenario_ids": ["{{scenario_id_1}}"]
  }
}

### - METRICS ------------------------------------------------------------------

### 6.1 REQUEST: Create run metrics
POST {{base_url}}/metrics/
Content-Type: application/json
Authorization: {{authorization}}

{
  "metrics": [
    {
      "run_id": "{{run_id}}",
      "data": {
        "score": 0.95,
        "confidence": 0.9,
        "duration": 0.92,
        "errors": 0.93,
        "cost": 0.91
      }
    }
  ]
}

### 6.2 Create scenario metrics
POST {{base_url}}/metrics/
Content-Type: application/json
Authorization: {{authorization}}

{
  "metrics": [
    {
      "run_id": "{{run_id}}",
      "scenario_id": "{{scenario_id_1}}",
      "data": {
        "score": 0.95,
        "confidence": 0.9,
        "duration": 0.92,
        "errors": 0.93,
        "cost": 0.91
      }
    },
    {
      "run_id": "{{run_id}}",
      "scenario_id": "{{scenario_id_2}}",
      "data": {
        "score": 0.95,
        "confidence": 0.9,
        "duration": 0.92,
        "errors": 0.93,
        "cost": 0.91
      }
    }
  ]
}


### 9. REQUEST: Get all metrics by run_id
POST {{base_url}}/metrics/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "metrics": {
    "run_id": "{{run_id}}"
  }
}

### 9. REQUEST: Get all metrics by run_id and scenario_id
POST {{base_url}}/metrics/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "metrics": {
    "run_id": "{{run_id}}",
    "scenario_ids": ["{{scenario_id_1}}"]
  }
}