repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff-format
      - id: ruff
  - repo: local
    hooks:
      - id: gitleaks-pre-commit
        name: gitleaks git (pre-commit, scan staged)
        entry: gitleaks --config .gitleaks.toml --exit-code 1 --verbose git --staged
        language: system
        pass_filenames: false
      - id: gitleaks-pre-push
        name: gitleaks git (staged only)
        entry: bash -c 'gitleaks --config .gitleaks.toml --exit-code 1 --verbose git --staged'
        language: system
        stages: [pre-push]
        pass_filenames: false
