api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  http:
    redirections:
      entryPoint:
        to: "web-secure"
        scheme: "https"
  web-secure:
    address: ":443"

providers:
  docker: {}

certificatesResolvers:
  myResolver:
    acme:
      email: "akrem.abayed@gmail.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"
