# Dockerfile
FROM python:3.9-slim-buster

WORKDIR /app

# Ensure pip and poetry are up to date
RUN pip install --upgrade pip \
    && pip install poetry

# Copy agenta_backend to app
COPY . /app/

# Project initialization:
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Expose 8000
EXPOSE 8000