@host = http://localhost
@token = replace-me
@base_url = {{host}}/api/preview/evaluators

###
# @name create_account
POST {{host}}/api/admin/account
Content-Type: application/json
Authorization: Access {{token}}

###
@user_id = {{create_account.response.body.user.id}}
@authorization = {{create_account.response.body.scopes[0].credentials}}

###
# CREATE EVALUATOR
# @name add_evaluator
POST {{base_url}}/
Content-Type: application/json
Authorization: {{authorization}}

{
    "evaluator": {
        "slug": "{{$guid}}",
        "name": "Evaluator Name",
        "description": "Evaluator description",
        "meta": {
            "tag1": "tag1",
            "tag2": "tag2"
        },
        "flags": {
            "is_custom": false,
            "is_human": true
        },
        "data": {
            "service": {
                "agenta": "v0.1.0",
                "format": {
                    "type": "object",
                    "properties": {
                        "id": { "type": "integer" },
                        "score": { "type": "number" },
                        "name": { "type": "string" },
                        "active": { "type": "boolean" },
                        "meta": {
                            "type": "object",
                            "properties": {
                                "version": { "type": "integer" },
                                "notes": { "type": "string" }
                            },
                            "required": ["version"]
                        }
                    },
                    "required": ["id", "name"]
                }
            }
        }
    }
}

###

@evaluator_id={{add_evaluator.response.body.evaluator.id}}

###
# fetch EVALUATOR
# @name get_evaluator
GET {{base_url}}/{{evaluator_id}}
Content-Type: application/json
Authorization: {{authorization}}

###
# EDIT EVALUATOR
# @name edit_evaluator
PUT {{base_url}}/{{evaluator_id}}
Content-Type: application/json
Authorization: {{authorization}}

{
    "evaluator": {
        "id": "{{evaluator_id}}",
        "name": "Another Evaluator Name",
        "description": "Another Evaluator description",
        "meta": {
            "tag1": "tag3",
            "tag2": "tag2",
            "tag3": "tag1"
        },
        "flags": {
            "is_custom": false,
            "is_human": false
        },
        "data": {
            "service": {
                "agenta": "v0.1.0",
                "format": {
                    "type": "object",
                    "properties": {
                        "id": { "type": "integer" },
                        "score": { "type": "number" },
                        "name": { "type": "string" },
                        "active": { "type": "boolean" },
                        "meta": {
                            "type": "object",
                            "properties": {
                                "version": { "type": "integer" },
                                "notes": { "type": "string" }
                            },
                            "required": ["version"]
                        }
                    },
                    "required": ["id", "name"]
                }
            }
        }
    }
}

###
# archive EVALUATOR
# @name archive_evaluator
POST {{base_url}}/{{evaluator_id}}/archive
Content-Type: application/json
Authorization: {{authorization}}


###
# unarchive EVALUATOR
# @name unarchive_evaluator
POST {{base_url}}/{{evaluator_id}}/unarchive
Content-Type: application/json
Authorization: {{authorization}}

###
# query EVALUATORS
# @name query_evaluators
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

###
# query EVALUATORS
# @name query_evaluators
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
    "evaluator": {
        "meta": {
            "tag1": "tag3",
            "tag2": "tag2",
            "tag3": "tag1"
        }
    }
}

###
# query EVALUATORS
# @name query_evaluators
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
    "evaluator": {
        "meta": {
            "tag1": "tag1",
            "tag2": "tag2"
        }
    }
}

###
# query EVALUATORS
# @name query_evaluators
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
    "evaluator": {
        "flags": {
            "is_human": true
        }
    }
}


###
# query EVALUATORS
# @name query_evaluators
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
    "evaluator": {
        "flags": {
            "is_human": false
        }
    }
}

###
# query EVALUATORS
# @name query_evaluators
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
    "evaluator": {
        "flags": {
            "is_evaluator": false
        }
    }
}