FROM python:3.8-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install fastapi uvicorn python-dotenv
EXPOSE 80

CMD ["python", "main.py"]
# uvicorn agenta_backend.main:app --reload --host 0.0.0.0 --port 8881
# TODO: add root_path as env variable and give it to the docker to solve the docs issue