FROM public.ecr.aws/s2t9a1r1/agentaai/lambda_templates_public:main

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install --no-cache-dir --disable-pip-version-check -r requirements.txt
RUN pip install --no-cache-dir --disable-pip-version-check mangum
RUN pip install --no-cache-dir --disable-pip-version-check -U agenta
COPY . ${LAMBDA_TASK_ROOT}

CMD [ "lambda_function.handler" ]
