FROM devgenix/agenta-llm-template:latest

ARG ROOT_PATH=/
ENV ROOT_PATH=${ROOT_PATH}

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

CMD ["./entrypoint.sh"]
# uvicorn agenta_backend.main:app --reload --host 0.0.0.0 --port 8881
# TODO: add root_path as env variable and give it to the docker to solve the docs issue