FROM public.ecr.aws/lambda/python:3.11

RUN pip install --upgrade pip \
    && pip install --no-cache-dir agenta openai python-dotenv fastapi uvicorn mangum

# Copy function code
COPY . ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.handler" ]
