FROM public.ecr.aws/s2t9a1r1/agentaai/lambda_templates_public:main

RUN pip install --upgrade pip \
    && pip install --no-cache-dir agenta openai python-dotenv fastapi uvicorn mangum

# Copy function code
COPY . ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.handler" ]
