{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agenta.fullname" . }}
  labels:
    {{- include "agenta.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          {{- if .Values.api.enabled }}
          - path: {{ .Values.ingress.paths.api.path }}
            pathType: {{ .Values.ingress.paths.api.pathType }}
            backend:
              service:
                name: {{ include "agenta.fullname" . }}-api
                port:
                  name: http
          {{- end }}
          {{- if .Values.services.enabled }}
          - path: {{ .Values.ingress.paths.services.path }}
            pathType: {{ .Values.ingress.paths.services.pathType }}
            backend:
              service:
                name: {{ include "agenta.fullname" . }}-services
                port:
                  name: http
          {{- end }}
          {{- if .Values.web.enabled }}
          - path: {{ .Values.ingress.paths.web.path }}
            pathType: {{ .Values.ingress.paths.web.pathType }}
            backend:
              service:
                name: {{ include "agenta.fullname" . }}-web
                port:
                  name: http
          {{- end }}
{{- end }}
