{{- include "agenta.validatePgauthSecret" . -}}
{{- if and .Values.postgresql.enabled (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agenta.pgauthSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agenta.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
{{- end }}
