{{- if .Values.services.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenta.fullname" . }}-services
  labels:
    {{- include "agenta.labels" . | nindent 4 }}
    app.kubernetes.io/component: services
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agenta.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: services
{{- end }}
