{{- if .Values.supertokens.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenta.fullname" . }}-supertokens
  labels:
    {{- include "agenta.labels" . | nindent 4 }}
    app.kubernetes.io/component: supertokens
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.supertokens.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agenta.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: supertokens
{{- end }}
