FROM python:3.10-slim

ARG ROOT_PATH=/
ENV ROOT_PATH=${ROOT_PATH}

WORKDIR /app/

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY ./oss /app/oss/
    
ENV PYTHONPATH=/agenta-cli:$PYTHONPATH

EXPOSE 80
