

@host = http://localhost
@base_url = {{host}}/api/variants/configs

###

# @name fetch_config_by_variant_ref_1
GET {{base_url}}/fetch
Content-Type: application/json

{
    "variant_ref": {
        "slug": null,
        "version": null,
        "id": "0192a460-3292-7fd1-80ce-fb1a9c3e2456"
    }
}

###

# @name fetch_config_by_variant_ref_1_with_environment
GET {{base_url}}/fetch
Content-Type: application/json

{
    "variant_ref": {
        "slug": null,
        "version": null,
        "id": "0192a45d-5ba1-757e-a983-787a66a4e78d"
    }
}

###

# @name fetch_config_by_variant_ref_2
GET {{base_url}}/fetch
Content-Type: application/json

{
    "variant_ref": {
        "slug": "test",
        "version": 1,
        "id": null
    },
    "application_ref": {
        "slug": null,
        "version": null,
        "id": "0192a45d-511e-7d1a-aaca-20280c963b1f"
    }
}

###

# @name fetch_config_by_variant_ref_2_with_environment
GET {{base_url}}/fetch
Content-Type: application/json

{
    "variant_ref": {
        "slug": "default",
        "version": 1,
        "id": null
    },
    "application_ref": {
        "slug": null,
        "version": null,
        "id": "0192a45d-511e-7d1a-aaca-20280c963b1f"
    }
}

###

# @name fetch_config_by_variant_ref_3
GET {{base_url}}/fetch
Content-Type: application/json

{
    "variant_ref": {
        "slug": "test",
        "version": 1,
        "id": null
    },
    "application_ref": {
        "slug": "test",
        "version": null,
        "id": null
    }
}

###

# @name fetch_config_by_variant_ref_3_with_environment
GET {{base_url}}/fetch
Content-Type: application/json

{
    "variant_ref": {
        "slug": "default",
        "version": 1,
        "id": null
    },
    "application_ref": {
        "slug": "test",
        "version": null,
        "id": null
    }
}

###

# @name fetch_config_by_variant_ref_4
GET {{base_url}}/fetch
Content-Type: application/json

{
    "variant_ref": {
        "slug": "test",
        "version": null,
        "id": null
    },
    "application_ref": {
        "slug": "test",
        "version": null,
        "id": null
    }
}

###

# @name fetch_prompt_by_env_ref_1
GET {{base_url}}/fetch
Content-Type: application/json

{
    "env_ref": {
        "commit_id": "01929c13-6af2-7b10-a51d-d99fccc1732b",
        "id": null,
        "version": null
    }
}

###

# @name fetch_prompt_by_env_ref_2
GET {{base_url}}/fetch
Content-Type: application/json

{
    "env_ref": {
        "id": "01929c13-638d-731f-b35a-954f252dcde8",
        "version": 1,
        "commit_id": null
    }
}

###

# @name fork_prompt_by_prompt_ref_1
POST {{base_url}}/fork
Content-Type: application/json

{
    "prompt_ref": {
        "commit_id": "01929c14-53d3-7f7f-9a42-66560c57399a",
        "id": null,
        "version": null
    }
}

###

# @name fork_prompt_by_prompt_ref_2
POST {{base_url}}/fork
Content-Type: application/json

{
    "prompt_ref": {
        "id": "01929c22-367d-7d9b-85a6-e6572f8ac63d",
        "version": 1,
        "commit_id": null
    }
}

###

# @name fork_prompt_by_env_ref_1
POST {{base_url}}/fork
Content-Type: application/json

{
    "env_ref": {
        "commit_id": "01929c13-6af2-7b10-a51d-d99fccc1732b",
        "id": null,
        "version": null
    }
}

###

# @name fork_prompt_by_env_ref_2
POST {{base_url}}/fork
Content-Type: application/json

{
    "env_ref": {
        "id": "01929c13-638d-731f-b35a-954f252dcde8",
        "version": 1,
        "commit_id": null
    }
}

###

# @name commit_prompt
POST {{base_url}}/commit
Content-Type: application/json

{ 
    "ref": {
        "id": "01929c2a-7ca4-774a-a8a9-f60c20dcbc81",
        "version": 1,
        "commit_id": "01929c2a-7cbc-7684-9c86-c502ce1a42f5"
    },
    "url": "http://localhost/01929c11-6d6a-78c8-985c-f84ea136dac2/test/app",
    "params": {
        "model": "gpt-3.5-turbo",
        "top_p": 1.0,
        "force_json": 0,
        "max_tokens": -1,
        "prompt_user": "What is the capital of {country}?",
        "temperature": 1.0,
        "prompt_system": "You are an expert in geography.",
        "presence_penalty": 0.0,
        "frequence_penalty": 0.0
    },
    "app_id": "01929c13-636b-79cd-b087-a652649bba75",
    "env_ref": null,
    "env_name": null
}

###

# @name deploy_prompt_by_env_ref_1
POST {{base_url}}/deploy
Content-Type: application/json

{ 
    "prompt_ref": {
        "id": "01929c2a-7ca4-774a-a8a9-f60c20dcbc81",
        "version": 1,
        "commit_id": "01929c2a-7cbc-7684-9c86-c502ce1a42f5"
    },
    "env_ref": {
        "commit_id": "01929c13-6af2-7b10-a51d-d99fccc1732b",
        "id": null,
        "version": null
    }
}