/**
 * generate-phosphor-catalog.ts — emit the agent-icon catalog from @phosphor-icons/core.
 *
 * The agent icon picker lets a user choose any Phosphor icon. Importing the React barrel to
 * do that would defeat tree-shaking (4.8 MB into the entry chunk), and a per-icon dynamic
 * import would emit ~1512 chunks. So we ship the raw `regular`-weight path data instead: one
 * generated module, lazily imported by the picker only.
 *
 * Only the `regular` weight is read, which is what enforces the outline-only rule — no other
 * weight exists in the output.
 *
 * Run: pnpm generate:phosphor-catalog   (from web/)
 */
import {readdirSync, readFileSync, mkdirSync, writeFileSync} from "fs"
import {dirname, resolve as pathResolve} from "path"
import {fileURLToPath} from "url"

import {icons} from "@phosphor-icons/core"

const HERE = dirname(fileURLToPath(import.meta.url)) // web/scripts
const WEB = pathResolve(HERE, "..") // web
const ASSETS = pathResolve(WEB, "node_modules/@phosphor-icons/core/assets/regular")
const OUT = pathResolve(WEB, "packages/agenta-ui/src/agent-icon/catalog.generated.ts")

/** Everything between the outer `<svg …>` and `</svg>` — the shapes, without the wrapper. */
const innerMarkup = (svg: string): string =>
    svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "")

const available = new Set(
    readdirSync(ASSETS)
        .filter((file) => file.endsWith(".svg"))
        .map((file) => file.slice(0, -".svg".length)),
)

const missing: string[] = []
const entries = icons
    .filter((icon) => {
        if (available.has(icon.name)) return true
        missing.push(icon.name)
        return false
    })
    .map((icon) => ({
        name: icon.name,
        tags: icon.tags ?? [],
        categories: (icon.categories ?? []) as string[],
        path: innerMarkup(readFileSync(pathResolve(ASSETS, `${icon.name}.svg`), "utf8")).trim(),
    }))

const body = entries
    .map(
        (entry) =>
            `    {\n` +
            `        name: ${JSON.stringify(entry.name)},\n` +
            `        tags: ${JSON.stringify(entry.tags)},\n` +
            `        categories: ${JSON.stringify(entry.categories)},\n` +
            `        path: ${JSON.stringify(entry.path)},\n` +
            `    },`,
    )
    .join("\n")

const file = `/**
 * GENERATED by scripts/generate-phosphor-catalog.ts from @phosphor-icons/core.
 * Do not hand-edit — run \`pnpm generate:phosphor-catalog\` from web/ instead.
 *
 * \`regular\` weight only: the agent icon is outline-only by rule, and generating one weight is
 * what enforces it. \`path\` is the inner markup of the icon's 0 0 256 256 viewBox.
 */

export interface PhosphorCatalogEntry {
    /** Kebab-case Phosphor name, e.g. "git-pull-request". This is what we persist. */
    name: string
    tags: string[]
    categories: string[]
    /** Inner SVG markup, drawn with \`fill="currentColor"\`. */
    path: string
}

export const phosphorCatalog: PhosphorCatalogEntry[] = [
${body}
]
`

mkdirSync(dirname(OUT), {recursive: true})
writeFileSync(OUT, file, "utf8")

const kb = Math.round(Buffer.byteLength(file) / 1024)
console.log(`wrote ${entries.length} icons (${kb} KB) → ${OUT.replace(WEB + "/", "")}`)
if (missing.length)
    console.warn(`skipped ${missing.length} with no regular asset: ${missing.join(", ")}`)
