export {
    default as ChatMessageEditor,
    ChatMessageList,
    extractTextFromContent,
    extractDisplayTextFromMessage,
    hasAttachments,
    getAttachmentInfo,
    getAttachments,
    updateTextInContent,
    addImageToContent,
    addFileToContent,
    removeAttachmentFromContent,
    CHAT_MESSAGE_SCHEMA,
    CHAT_MESSAGES_ARRAY_SCHEMA,
    ToolMessageHeader,
} from "./ChatMessageEditor"
export type {
    ChatMessageEditorProps,
    ChatMessageListProps,
    SimpleChatMessage,
    MessageContent,
    MessageContentPart,
    TextContentPart,
    ImageContentPart,
    FileContentPart,
    ToolCall,
} from "./ChatMessageEditor"
