"""migrate old environments to new environments data structure

Revision ID: c9d0e1f2a3b4
Revises: b8c9d0e1f2a3
Create Date: 2025-05-15 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import context
from oss.databases.postgres.migrations.core.data_migrations.environments import (
    run_migration,
)

# revision identifiers, used by Alembic.
revision: str = "c9d0e1f2a3b4"
down_revision: Union[str, None] = "b8c9d0e1f2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    run_migration(sqlalchemy_url=context.config.get_main_option("sqlalchemy.url"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
