docker_registry_url="127.0.0.1:5001"
database_url="localhost:5432"
registry="agenta-server"
backend_endpoint="http://localhost/api"
allow_origins="http://localhost:3000,http://localhost:3001,http://54.93.214.89:3000"