@baseUrl = http://localhost
@service = completion-new-sdk
@application_id = 0194184e-e836-7e10-83a5-4f2c32927a21

### These request can be run using the Rest Client extension in vsCode

### Health Check
GET {{baseUrl}}/{{service}}/health

### OpenAPI
GET {{baseUrl}}/{{service}}/openapi.json

### Generate
POST {{baseUrl}}/{{service}}/test
Content-Type: application/json

{
    "ag_config": {
        "temperature": 0.7,
        "model": "gpt-3.5",
        "max_tokens": 256,
        "prompt_system": "You are an expert in linguistics.",
        "prompt_user": "What is the meaning of {word}?",
        "top_p": 0.95,
        "frequence_penalty": 0.5,
        "presence_penalty": 0.5,
        "force_json": false
    },
    "inputs": {
        "word": "language"
    }
}

### Run
POST {{baseUrl}}/{{service}}/run?application_id={{application_id}}&variant_slug=default
Content-Type: application/json

{
    "inputs": {
        "country": "Germany"
    }
}


### Run (baggage)
POST {{baseUrl}}/{{service}}/run
Content-Type: application/json
Baggage: application_id={{application_id}}, variant_slug=default

{
    "inputs": {
        "country": "Germany"
    }
}
