@baseUrl = http://localhost
@service = completion-old-sdk

### These request can be run using the Rest Client extension in vsCode

### Health Check
GET {{baseUrl}}/{{service}}/health HTTP/1.1

### OpenAPI
GET {{baseUrl}}/{{service}}/openapi.json HTTP/1.1

### Generate
POST {{baseUrl}}/{{service}}/generate HTTP/1.1
Content-Type: application/json

{
    "temperature": 1.0,
    "model": "gpt-3.5-turbo",
    "max_tokens": -1,
    "prompt_system": "You are an expert in geography.",
    "prompt_user": "What is the capital of {country}?",
    "top_p": 1.0,
    "frequence_penalty": 0.0,
    "presence_penalty": 0.0,
    "force_json": false,
    "inputs": {
        "country": "France"
    }
}

### Playground Run
POST {{baseUrl}}/{{service}}/playground/run HTTP/1.1
Content-Type: application/json

{
    "temperature": 1.0,
    "model": "gpt-3.5-turbo",
    "max_tokens": -1,
    "prompt_system": "You are an expert in geography.",
    "prompt_user": "What is the capital of {country}?",
    "top_p": 1.0,
    "frequence_penalty": 0.0,
    "presence_penalty": 0.0,
    "force_json": false,
    "inputs": {
        "country": "Spain"
    }
}

### Generate Deployed
POST {{baseUrl}}/{{service}}/generate_deployed HTTP/1.1
Content-Type: application/json

{
    "inputs": {
        "country": "Italy"
    },
    "config": "default",
    "environment": "production"
}

### Run
POST {{baseUrl}}/{{service}}/run HTTP/1.1
Content-Type: application/json

{
    "inputs": {
        "country": "Germany"
    },
    "config": "default",
    "environment": "production"
}
