# This file was auto-generated by Fern from our API Definition.

import typing

LmProvidersEnum = typing.Union[
    typing.Literal[
        "OPENAI_API_KEY",
        "MISTRAL_API_KEY",
        "COHERE_API_KEY",
        "ANTHROPIC_API_KEY",
        "ANYSCALE_API_KEY",
        "PERPLEXITYAI_API_KEY",
        "DEEPINFRA_API_KEY",
        "TOGETHERAI_API_KEY",
        "ALEPHALPHA_API_KEY",
        "OPENROUTER_API_KEY",
        "GROQ_API_KEY",
        "GEMINI_API_KEY",
    ],
    typing.Any,
]
