# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .role import Role
from .reference import Reference
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class ProjectScope(UniversalBaseModel):
    credentials: str
    role: Role
    tier: str
    user: Reference
    project: Reference
    workspace: Reference
    organization: Reference

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
