# This file was auto-generated by Fern from our API Definition.

import typing

ProviderKind = typing.Union[
    typing.Literal[
        "openai",
        "cohere",
        "anyscale",
        "deepinfra",
        "alephalpha",
        "groq",
        "mistral",
        "anthropic",
        "perplexityai",
        "togetherai",
        "openrouter",
        "gemini",
    ],
    typing.Any,
]
