# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class Status(str, enum.Enum):
    """
    An enumeration.
    """

    INITIATED = "INITIATED"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"

    def visit(
        self,
        initiated: typing.Callable[[], T_Result],
        success: typing.Callable[[], T_Result],
        failure: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is Status.INITIATED:
            return initiated()
        if self is Status.SUCCESS:
            return success()
        if self is Status.FAILURE:
            return failure()
