# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_ref import EntityRef


class AdminUserIdentityCreateDto(UniversalBaseModel):
    user_ref: typing.Optional[EntityRef] = None
    method: str
    subject: str
    domain: typing.Optional[str] = None
    email: typing.Optional[str] = None
    password: typing.Optional[str] = None
    verified: typing.Optional[bool] = None
    provider_user_id: typing.Optional[str] = None
    claims: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
