# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .channel_buttons import ChannelButtons
from .channel_controls import ChannelControls
from .channel_files import ChannelFiles
from .channel_text import ChannelText


class ChannelRendering(UniversalBaseModel):
    controls: typing.Optional[ChannelControls] = None
    buttons: typing.Optional[ChannelButtons] = None
    text: typing.Optional[ChannelText] = None
    files: typing.Optional[ChannelFiles] = None
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
