# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .channel_space_kind import ChannelSpaceKind


class ChannelSpaceCandidate(UniversalBaseModel):
    """
    One row in the configuration pick-list. Not an entity: no id, no
    lifecycle, nothing persisted until the operator chooses.
    """
    kind: ChannelSpaceKind
    external_locator: typing.Dict[str, typing.Any]
    display_name: typing.Optional[str] = None
    is_configured: typing.Optional[bool] = None
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
