# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CommitWarning(UniversalBaseModel):
    """
    One thing the caller should know about a commit that still succeeded.
    
    The codes are the engine's (change-set.md 7.1) plus `no_change`, which the commit
    wrapper owns. `target` carries contract-shaped segments, so a caller can act on the
    warning without parsing its prose.
    """
    code: str
    message: str
    target: typing.Optional[typing.List[typing.Any]] = None
    operation_index: typing.Optional[int] = None
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
