# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import (
    IS_PYDANTIC_V2,
    UniversalBaseModel,
    update_forward_refs,
)
from .formatting import Formatting
from .trace_input import TraceInput
from .windowing import Windowing


class QueryRevisionDataInput(UniversalBaseModel):
    formatting: typing.Optional[Formatting] = None
    filtering: typing.Optional["FilteringInput"] = None
    windowing: typing.Optional[Windowing] = None
    trace_ids: typing.Optional[typing.List[str]] = None
    traces: typing.Optional[typing.List[TraceInput]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .filtering_input import FilteringInput  # noqa: E402, I001
from .filtering_input_conditions_item import FilteringInputConditionsItem  # noqa: E402, I001

update_forward_refs(
    QueryRevisionDataInput,
    FilteringInput=FilteringInput,
    FilteringInputConditionsItem=FilteringInputConditionsItem,
)
