# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .commit_warning import CommitWarning
from .read_config_revision import ReadConfigRevision


class ReadConfigResponse(UniversalBaseModel):
    revision: ReadConfigRevision
    base_revision_id: str = pydantic.Field()
    """
    Copy this into your next commit's `base_revision_id`.
    """
    
    is_draft: typing.Optional[bool] = None
    path: typing.Optional[typing.List[typing.Any]] = None
    value: typing.Optional[typing.Any] = None
    bytes: typing.Optional[int] = None
    warnings: typing.Optional[typing.List[CommitWarning]] = None
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
