# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .windowing import Windowing


class SessionIdsResponse(UniversalBaseModel):
    support_id: typing.Optional[str] = None
    support_ts: typing.Optional[dt.datetime] = None
    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of session IDs in this page.
    """
    
    session_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Distinct values of `ag.session.id` in this page.
    """
    
    windowing: typing.Optional[Windowing] = pydantic.Field(default=None)
    """
    Cursor for the next page. Pass verbatim as `windowing.next`.
    """
    
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
