# This file was auto-generated by Fern from our API Definition.

import typing

from .connection_create_data import ConnectionCreateData
from .full_json_input import FullJsonInput

ToolConnectionCreateData = typing.Union[ConnectionCreateData, typing.Dict[str, typing.Optional[FullJsonInput]]]
