# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ToolDefinition(UniversalBaseModel):
    name: str
    title: str
    description: str
    input_schema: typing_extensions.Annotated[
        typing.Dict[str, typing.Any], FieldMetadata(alias="inputSchema")
    ] = pydantic.Field(alias="inputSchema")
    output_schema: typing_extensions.Annotated[
        typing.Dict[str, typing.Any], FieldMetadata(alias="outputSchema")
    ] = pydantic.Field(alias="outputSchema")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
