# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .trace_input import TraceInput


class TracesRequest(UniversalBaseModel):
    """
    Ingest payload in the canonical `Traces` list shape.
    
    Used by `POST /traces/ingest`. Each entry is one trace with its
    `trace_id` and a nested `spans` tree.
    """
    traces: typing.Optional[typing.List[TraceInput]] = pydantic.Field(default=None)
    """
    List of trace records. Each record is a `trace_id` plus the nested `spans` tree. Equivalent to the map-shaped payload accepted by `POST /tracing/spans/ingest`.
    """
    
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
update_forward_refs(TracesRequest)
