# This file was auto-generated by Fern from our API Definition.

import typing

WebhookEventType = typing.Union[
    typing.Literal["environments.revisions.committed", "webhooks.subscriptions.tested"],
    typing.Any,
]
