# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_revision_operation_match_mode import WorkflowRevisionOperationMatchMode
from .workflow_revision_operation_operation import WorkflowRevisionOperationOperation


class WorkflowRevisionOperation(UniversalBaseModel):
    """
    One ordered operation. The new delta arm (agent-config-editing, contract 3.2).
    
    ``extra="forbid"`` applies to this NEW model only. The legacy ``set``/``remove`` arm
    stays permissive on purpose: tightening it would reject payloads that shipped
    playbooks send today and that the server has always ignored.
    """
    operation: WorkflowRevisionOperationOperation
    target: typing.List[typing.Any]
    value: typing.Optional[typing.Any] = None
    edits: typing.Optional[typing.List[typing.Dict[str, str]]] = None
    match_mode: typing.Optional[WorkflowRevisionOperationMatchMode] = None
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
