export const FILTER_COLUMNS = [
    {type: "exists", value: "tree.id", label: "Tree ID"},
    {type: "exists", value: "node.id", label: "Node ID"},
    {type: "exists", value: "node.type", label: "Node Type"},
    {type: "exists", value: "node.name", label: "Node Name"},
    {type: "number", value: "metrics.acc.duration.total", label: "Duration (ms)"},
    {type: "number", value: "metrics.acc.costs.total", label: "Cost ($)"},
    {type: "number", value: "metrics.acc.tokens.total", label: "Total Tokens"},
    {type: "number", value: "metrics.acc.tokens.prompt", label: "Prompt Tokens"},
    {type: "number", value: "metrics.acc.tokens.completion", label: "Completion Tokens"},
    {type: "exists", value: "status.code", label: "Status Code"},
    {type: "exists", value: "status.message", label: "Status Message"},
    {type: "exists", value: "exception.type", label: "Exception Type"},
    {type: "exists", value: "exception.message", label: "Exception Message"},
    {type: "exists", value: "exception.stacktrace", label: "Exception Stacktrace"},
    {type: "string", value: "content", label: "Content"},
    {type: "exists", value: "refs.application.id", label: "Application ID"},
    {type: "exists", value: "refs.application.slug", label: "Application Slug"},
    {type: "exists", value: "refs.variant.id", label: "Variant ID"},
    {type: "exists", value: "refs.variant.slug", label: "Variant Slug"},
    {type: "exists", value: "refs.variant.version", label: "Variant Version"},
    {type: "exists", value: "refs.environment.id", label: "Environment ID"},
    {type: "exists", value: "refs.environment.slug", label: "Environment Slug"},
    {type: "exists", value: "refs.environment.version", label: "Environment Version"},
]
