import {bare, code, key, modChord} from "../chord"
import {SECTION_IDS} from "../sections"

import {defineShortcuts, id} from "./helpers"

/** The context rail and the files pane: two components, one place a user looks. */
export const SURFACE_SHORTCUTS = defineShortcuts([
    {
        id: id("context.expandRail"),
        section: SECTION_IDS.contextAndFiles,
        chords: [bare(key("Enter")), bare(key("Space"))],
        label: "Expand the context rail",
        context: "on the collapsed rail",
        inlineHint: "never",
        order: 10,
    },
    {
        id: id("files.move"),
        section: SECTION_IDS.contextAndFiles,
        chords: [bare(key("ArrowDown")), bare(key("ArrowUp"))],
        label: "Move through rows",
        inlineHint: "never",
        order: 20,
    },
    {
        id: id("files.edge"),
        section: SECTION_IDS.contextAndFiles,
        chords: [bare(key("Home")), bare(key("End"))],
        label: "First or last row",
        inlineHint: "never",
        order: 21,
    },
    {
        id: id("files.expand"),
        section: SECTION_IDS.contextAndFiles,
        chords: [bare(key("ArrowRight"))],
        label: "Expand a folder, or step into it",
        inlineHint: "never",
        order: 30,
    },
    {
        id: id("files.collapse"),
        section: SECTION_IDS.contextAndFiles,
        chords: [bare(key("ArrowLeft"))],
        label: "Collapse a folder, or step to its parent",
        inlineHint: "never",
        order: 31,
    },
    {
        id: id("files.openTile"),
        section: SECTION_IDS.contextAndFiles,
        chords: [modChord(key("ArrowDown"))],
        label: "Open the focused tile",
        inlineHint: "never",
        order: 40,
    },
    {
        id: id("files.parentFolder"),
        section: SECTION_IDS.contextAndFiles,
        chords: [modChord(key("ArrowUp"))],
        label: "Go to the parent folder",
        inlineHint: "never",
        order: 41,
    },
    {
        id: id("files.zoomPreview"),
        section: SECTION_IDS.contextAndFiles,
        chords: [bare(key("Enter")), bare(key("Space"))],
        label: "Zoom an image preview",
        context: "on a focused preview",
        inlineHint: "never",
        order: 50,
    },
    {
        id: id("files.menu"),
        section: SECTION_IDS.contextAndFiles,
        chords: [bare(key("ContextMenu")), bare(key("F10"), {shift: "required"})],
        label: "Open the file menu",
        inlineHint: "never",
        order: 51,
    },
])

export const CONFIG_PANEL_SHORTCUTS = defineShortcuts([
    {
        id: id("config.activate"),
        section: SECTION_IDS.configPanel,
        chords: [bare(key("Enter")), bare(key("Space"))],
        label: "Open the highlighted item",
        context: "on a field, section, skill, or trigger row",
        inlineHint: "never",
        order: 10,
    },
    {
        id: id("config.choiceCard.pick"),
        section: SECTION_IDS.configPanel,
        chords: Array.from({length: 9}, (_, index) => bare(code(`Digit${index + 1}`))),
        label: "Pick a choice card by number",
        inlineHint: "never",
        order: 20,
    },
    {
        id: id("config.choiceCard.move"),
        section: SECTION_IDS.configPanel,
        chords: [bare(key("ArrowDown")), bare(key("ArrowUp"))],
        label: "Move through choice cards",
        inlineHint: "never",
        order: 21,
    },
    {
        id: id("config.choiceCard.select"),
        section: SECTION_IDS.configPanel,
        chords: [bare(key("Space")), bare(key("Enter"))],
        label: "Select a choice card",
        context: "on a focused card",
        inlineHint: "never",
        order: 22,
    },
    {
        id: id("config.chip.add"),
        section: SECTION_IDS.configPanel,
        chords: [bare(key("Enter"))],
        label: "Add a chip",
        context: "in a tags field",
        inlineHint: "never",
        guards: {typing: "allow"},
        order: 30,
    },
    {
        id: id("config.chip.removeLast"),
        section: SECTION_IDS.configPanel,
        chords: [bare(key("Backspace"))],
        label: "Remove the last chip",
        context: "on an empty input",
        inlineHint: "never",
        guards: {typing: "allow"},
        order: 31,
    },
    {
        id: id("config.commit"),
        section: SECTION_IDS.configPanel,
        chords: [bare(key("Enter"))],
        label: "Save a rename or provider key",
        context: "in a name or key field",
        inlineHint: "never",
        guards: {typing: "allow"},
        order: 40,
    },
    {
        id: id("config.closeDrawer"),
        section: SECTION_IDS.configPanel,
        chords: [bare(key("Escape"))],
        label: "Close a drawer",
        inlineHint: "never",
        order: 50,
    },
])
