# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .status import Status
from .webhook_delivery_data import WebhookDeliveryData


class WebhookDelivery(UniversalBaseModel):
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    deleted_at: typing.Optional[dt.datetime] = None
    created_by_id: typing.Optional[str] = None
    updated_by_id: typing.Optional[str] = None
    deleted_by_id: typing.Optional[str] = None
    id: typing.Optional[str] = None
    status: Status
    data: typing.Optional[WebhookDeliveryData] = None
    subscription_id: str
    event_id: str
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
