@host = http://localhost
@base_url = {{host}}/api
@access_token = replace-me

###

# @name create_account
POST {{base_url}}/admin/account
Content-Type: application/json
Authorization: Access {{access_token}}

{
  "user": {
    "name": "test_user",
    "email": "test@agenta.ai"
  },
  "scope": {
    "name": "Agenta (test)"
  }
}