# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.testcase_response import TestcaseResponse
from ..types.testcases_response import TestcasesResponse
from ..types.windowing import Windowing
from .raw_client import AsyncRawTestcasesClient, RawTestcasesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TestcasesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTestcasesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTestcasesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTestcasesClient
        """
        return self._raw_client

    def fetch_testcase(
        self, testcase_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TestcaseResponse:
        """
        Parameters
        ----------
        testcase_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestcaseResponse
            Successful Response

        Examples
        --------
        from agenta import AgentaApi

        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.testcases.fetch_testcase(
            testcase_id="testcase_id",
        )
        """
        _response = self._raw_client.fetch_testcase(testcase_id, request_options=request_options)
        return _response.data

    def query_testcases(
        self,
        *,
        testcase_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        testset_id: typing.Optional[str] = OMIT,
        testset_revision_id: typing.Optional[str] = OMIT,
        windowing: typing.Optional[Windowing] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestcasesResponse:
        """
        Parameters
        ----------
        testcase_ids : typing.Optional[typing.Sequence[str]]

        testset_id : typing.Optional[str]

        testset_revision_id : typing.Optional[str]

        windowing : typing.Optional[Windowing]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestcasesResponse
            Successful Response

        Examples
        --------
        from agenta import AgentaApi

        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.testcases.query_testcases()
        """
        _response = self._raw_client.query_testcases(
            testcase_ids=testcase_ids,
            testset_id=testset_id,
            testset_revision_id=testset_revision_id,
            windowing=windowing,
            request_options=request_options,
        )
        return _response.data


class AsyncTestcasesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTestcasesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTestcasesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTestcasesClient
        """
        return self._raw_client

    async def fetch_testcase(
        self, testcase_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TestcaseResponse:
        """
        Parameters
        ----------
        testcase_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestcaseResponse
            Successful Response

        Examples
        --------
        import asyncio

        from agenta import AsyncAgentaApi

        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.testcases.fetch_testcase(
                testcase_id="testcase_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_testcase(testcase_id, request_options=request_options)
        return _response.data

    async def query_testcases(
        self,
        *,
        testcase_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        testset_id: typing.Optional[str] = OMIT,
        testset_revision_id: typing.Optional[str] = OMIT,
        windowing: typing.Optional[Windowing] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestcasesResponse:
        """
        Parameters
        ----------
        testcase_ids : typing.Optional[typing.Sequence[str]]

        testset_id : typing.Optional[str]

        testset_revision_id : typing.Optional[str]

        windowing : typing.Optional[Windowing]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestcasesResponse
            Successful Response

        Examples
        --------
        import asyncio

        from agenta import AsyncAgentaApi

        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.testcases.query_testcases()


        asyncio.run(main())
        """
        _response = await self._raw_client.query_testcases(
            testcase_ids=testcase_ids,
            testset_id=testset_id,
            testset_revision_id=testset_revision_id,
            windowing=windowing,
            request_options=request_options,
        )
        return _response.data
