# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.analytics_response import AnalyticsResponse
from ..types.filtering_input import FilteringInput
from ..types.focus import Focus
from ..types.format import Format
from ..types.http_validation_error import HttpValidationError
from ..types.o_tel_link_input import OTelLinkInput
from ..types.reference import Reference
from ..types.session_ids_response import SessionIdsResponse
from ..types.simple_trace_create import SimpleTraceCreate
from ..types.simple_trace_edit import SimpleTraceEdit
from ..types.simple_trace_link_response import SimpleTraceLinkResponse
from ..types.simple_trace_query import SimpleTraceQuery
from ..types.simple_trace_response import SimpleTraceResponse
from ..types.simple_traces_response import SimpleTracesResponse
from ..types.span_response import SpanResponse
from ..types.spans_response import SpansResponse
from ..types.trace_id_response import TraceIdResponse
from ..types.trace_input import TraceInput
from ..types.trace_response import TraceResponse
from ..types.traces_response import TracesResponse
from ..types.user_ids_response import UserIdsResponse
from ..types.windowing import Windowing
from .types.query_spans_analytics_request_newest import QuerySpansAnalyticsRequestNewest
from .types.query_spans_analytics_request_oldest import QuerySpansAnalyticsRequestOldest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)
class RawTracesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
    
    def fetch_traces(self, *, trace_id: typing.Optional[typing.Sequence[str]] = None, trace_ids: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[TracesResponse]:
        """
        Parameters
        ----------
        trace_id : typing.Optional[typing.Sequence[str]]
        
        trace_ids : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[TracesResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "traces/",method="GET",
            params={"trace_id": trace_id, "trace_ids": trace_ids, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TracesResponse,
                    parse_obj_as(
                        type_ =TracesResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def create_trace(self, *, trace: typing.Optional[TraceInput] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[TraceIdResponse]:
        """
        Parameters
        ----------
        trace : typing.Optional[TraceInput]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[TraceIdResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "traces/",method="POST",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=typing.Optional[TraceInput], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceIdResponse,
                    parse_obj_as(
                        type_ =TraceIdResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def query_traces(self, *, filtering: typing.Optional[FilteringInput] = OMIT, windowing: typing.Optional[Windowing] = OMIT, query_ref: typing.Optional[Reference] = OMIT, query_variant_ref: typing.Optional[Reference] = OMIT, query_revision_ref: typing.Optional[Reference] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[TracesResponse]:
        """
        Parameters
        ----------
        filtering : typing.Optional[FilteringInput]
        
        windowing : typing.Optional[Windowing]
        
        query_ref : typing.Optional[Reference]
        
        query_variant_ref : typing.Optional[Reference]
        
        query_revision_ref : typing.Optional[Reference]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[TracesResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "traces/query",method="POST",
            json={
                "filtering": convert_and_respect_annotation_metadata(object_=filtering, annotation=typing.Optional[FilteringInput], direction="write"),
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
                "query_ref": convert_and_respect_annotation_metadata(object_=query_ref, annotation=typing.Optional[Reference], direction="write"),
                "query_variant_ref": convert_and_respect_annotation_metadata(object_=query_variant_ref, annotation=typing.Optional[Reference], direction="write"),
                "query_revision_ref": convert_and_respect_annotation_metadata(object_=query_revision_ref, annotation=typing.Optional[Reference], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TracesResponse,
                    parse_obj_as(
                        type_ =TracesResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def fetch_trace(self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[TraceResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[TraceResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"traces/{jsonable_encoder(trace_id)}",method="GET",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceResponse,
                    parse_obj_as(
                        type_ =TraceResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def edit_trace(self, trace_id: str, *, trace: typing.Optional[TraceInput] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[TraceIdResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        trace : typing.Optional[TraceInput]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[TraceIdResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"traces/{jsonable_encoder(trace_id)}",method="PUT",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=typing.Optional[TraceInput], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceIdResponse,
                    parse_obj_as(
                        type_ =TraceIdResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def delete_trace(self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[TraceIdResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[TraceIdResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"traces/{jsonable_encoder(trace_id)}",method="DELETE",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceIdResponse,
                    parse_obj_as(
                        type_ =TraceIdResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def fetch_spans(self, *, trace_id: typing.Optional[typing.Sequence[str]] = None, trace_ids: typing.Optional[str] = None, span_id: typing.Optional[typing.Sequence[str]] = None, span_ids: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SpansResponse]:
        """
        Parameters
        ----------
        trace_id : typing.Optional[typing.Sequence[str]]
        
        trace_ids : typing.Optional[str]
        
        span_id : typing.Optional[typing.Sequence[str]]
        
        span_ids : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SpansResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "spans/",method="GET",
            params={"trace_id": trace_id, "trace_ids": trace_ids, "span_id": span_id, "span_ids": span_ids, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SpansResponse,
                    parse_obj_as(
                        type_ =SpansResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def query_spans(self, *, filtering: typing.Optional[FilteringInput] = OMIT, windowing: typing.Optional[Windowing] = OMIT, query_ref: typing.Optional[Reference] = OMIT, query_variant_ref: typing.Optional[Reference] = OMIT, query_revision_ref: typing.Optional[Reference] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SpansResponse]:
        """
        Parameters
        ----------
        filtering : typing.Optional[FilteringInput]
        
        windowing : typing.Optional[Windowing]
        
        query_ref : typing.Optional[Reference]
        
        query_variant_ref : typing.Optional[Reference]
        
        query_revision_ref : typing.Optional[Reference]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SpansResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "spans/query",method="POST",
            json={
                "filtering": convert_and_respect_annotation_metadata(object_=filtering, annotation=typing.Optional[FilteringInput], direction="write"),
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
                "query_ref": convert_and_respect_annotation_metadata(object_=query_ref, annotation=typing.Optional[Reference], direction="write"),
                "query_variant_ref": convert_and_respect_annotation_metadata(object_=query_variant_ref, annotation=typing.Optional[Reference], direction="write"),
                "query_revision_ref": convert_and_respect_annotation_metadata(object_=query_revision_ref, annotation=typing.Optional[Reference], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SpansResponse,
                    parse_obj_as(
                        type_ =SpansResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def query_spans_analytics(self, *, focus: typing.Optional[Focus] = None, format: typing.Optional[Format] = None, oldest: typing.Optional[QuerySpansAnalyticsRequestOldest] = None, newest: typing.Optional[QuerySpansAnalyticsRequestNewest] = None, interval: typing.Optional[int] = None, rate: typing.Optional[float] = None, filter: typing.Optional[str] = None, specs: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[AnalyticsResponse]:
        """
        Parameters
        ----------
        focus : typing.Optional[Focus]
        
        format : typing.Optional[Format]
        
        oldest : typing.Optional[QuerySpansAnalyticsRequestOldest]
        
        newest : typing.Optional[QuerySpansAnalyticsRequestNewest]
        
        interval : typing.Optional[int]
        
        rate : typing.Optional[float]
        
        filter : typing.Optional[str]
        
        specs : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[AnalyticsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "spans/analytics/query",method="POST",
            params={"focus": focus, "format": format, "oldest": oldest, "newest": newest, "interval": interval, "rate": rate, "filter": filter, "specs": specs, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AnalyticsResponse,
                    parse_obj_as(
                        type_ =AnalyticsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def query_spans_sessions(self, *, realtime: typing.Optional[bool] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SessionIdsResponse]:
        """
        Parameters
        ----------
        realtime : typing.Optional[bool]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SessionIdsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "spans/sessions/query",method="POST",
            json={
                "realtime": realtime,
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SessionIdsResponse,
                    parse_obj_as(
                        type_ =SessionIdsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def query_spans_users(self, *, realtime: typing.Optional[bool] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[UserIdsResponse]:
        """
        Parameters
        ----------
        realtime : typing.Optional[bool]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[UserIdsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "spans/users/query",method="POST",
            json={
                "realtime": realtime,
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UserIdsResponse,
                    parse_obj_as(
                        type_ =UserIdsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def fetch_span(self, trace_id: str, span_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SpanResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        span_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SpanResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"spans/{jsonable_encoder(trace_id)}/{jsonable_encoder(span_id)}",method="GET",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SpanResponse,
                    parse_obj_as(
                        type_ =SpanResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def create_simple_trace(self, *, trace: SimpleTraceCreate, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SimpleTraceResponse]:
        """
        Parameters
        ----------
        trace : SimpleTraceCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SimpleTraceResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "simple/traces/",method="POST",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=SimpleTraceCreate, direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTraceResponse,
                    parse_obj_as(
                        type_ =SimpleTraceResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def fetch_simple_trace(self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SimpleTraceResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SimpleTraceResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"simple/traces/{jsonable_encoder(trace_id)}",method="GET",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTraceResponse,
                    parse_obj_as(
                        type_ =SimpleTraceResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def delete_simple_trace(self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SimpleTraceLinkResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SimpleTraceLinkResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"simple/traces/{jsonable_encoder(trace_id)}",method="DELETE",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTraceLinkResponse,
                    parse_obj_as(
                        type_ =SimpleTraceLinkResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def edit_simple_trace(self, trace_id: str, *, trace: SimpleTraceEdit, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SimpleTraceResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        trace : SimpleTraceEdit
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SimpleTraceResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"simple/traces/{jsonable_encoder(trace_id)}",method="PATCH",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=SimpleTraceEdit, direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTraceResponse,
                    parse_obj_as(
                        type_ =SimpleTraceResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def query_simple_traces(self, *, trace: typing.Optional[SimpleTraceQuery] = OMIT, links: typing.Optional[typing.Sequence[OTelLinkInput]] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SimpleTracesResponse]:
        """
        Parameters
        ----------
        trace : typing.Optional[SimpleTraceQuery]
        
        links : typing.Optional[typing.Sequence[OTelLinkInput]]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[SimpleTracesResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "simple/traces/query",method="POST",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=typing.Optional[SimpleTraceQuery], direction="write"),
                "links": convert_and_respect_annotation_metadata(object_=links, annotation=typing.Optional[typing.Sequence[OTelLinkInput]], direction="write"),
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTracesResponse,
                    parse_obj_as(
                        type_ =SimpleTracesResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
class AsyncRawTracesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
    
    async def fetch_traces(self, *, trace_id: typing.Optional[typing.Sequence[str]] = None, trace_ids: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[TracesResponse]:
        """
        Parameters
        ----------
        trace_id : typing.Optional[typing.Sequence[str]]
        
        trace_ids : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[TracesResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "traces/",method="GET",
            params={"trace_id": trace_id, "trace_ids": trace_ids, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TracesResponse,
                    parse_obj_as(
                        type_ =TracesResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def create_trace(self, *, trace: typing.Optional[TraceInput] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[TraceIdResponse]:
        """
        Parameters
        ----------
        trace : typing.Optional[TraceInput]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[TraceIdResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "traces/",method="POST",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=typing.Optional[TraceInput], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceIdResponse,
                    parse_obj_as(
                        type_ =TraceIdResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def query_traces(self, *, filtering: typing.Optional[FilteringInput] = OMIT, windowing: typing.Optional[Windowing] = OMIT, query_ref: typing.Optional[Reference] = OMIT, query_variant_ref: typing.Optional[Reference] = OMIT, query_revision_ref: typing.Optional[Reference] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[TracesResponse]:
        """
        Parameters
        ----------
        filtering : typing.Optional[FilteringInput]
        
        windowing : typing.Optional[Windowing]
        
        query_ref : typing.Optional[Reference]
        
        query_variant_ref : typing.Optional[Reference]
        
        query_revision_ref : typing.Optional[Reference]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[TracesResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "traces/query",method="POST",
            json={
                "filtering": convert_and_respect_annotation_metadata(object_=filtering, annotation=typing.Optional[FilteringInput], direction="write"),
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
                "query_ref": convert_and_respect_annotation_metadata(object_=query_ref, annotation=typing.Optional[Reference], direction="write"),
                "query_variant_ref": convert_and_respect_annotation_metadata(object_=query_variant_ref, annotation=typing.Optional[Reference], direction="write"),
                "query_revision_ref": convert_and_respect_annotation_metadata(object_=query_revision_ref, annotation=typing.Optional[Reference], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TracesResponse,
                    parse_obj_as(
                        type_ =TracesResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def fetch_trace(self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[TraceResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[TraceResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"traces/{jsonable_encoder(trace_id)}",method="GET",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceResponse,
                    parse_obj_as(
                        type_ =TraceResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def edit_trace(self, trace_id: str, *, trace: typing.Optional[TraceInput] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[TraceIdResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        trace : typing.Optional[TraceInput]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[TraceIdResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"traces/{jsonable_encoder(trace_id)}",method="PUT",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=typing.Optional[TraceInput], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceIdResponse,
                    parse_obj_as(
                        type_ =TraceIdResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def delete_trace(self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[TraceIdResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[TraceIdResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"traces/{jsonable_encoder(trace_id)}",method="DELETE",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceIdResponse,
                    parse_obj_as(
                        type_ =TraceIdResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def fetch_spans(self, *, trace_id: typing.Optional[typing.Sequence[str]] = None, trace_ids: typing.Optional[str] = None, span_id: typing.Optional[typing.Sequence[str]] = None, span_ids: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SpansResponse]:
        """
        Parameters
        ----------
        trace_id : typing.Optional[typing.Sequence[str]]
        
        trace_ids : typing.Optional[str]
        
        span_id : typing.Optional[typing.Sequence[str]]
        
        span_ids : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SpansResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "spans/",method="GET",
            params={"trace_id": trace_id, "trace_ids": trace_ids, "span_id": span_id, "span_ids": span_ids, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SpansResponse,
                    parse_obj_as(
                        type_ =SpansResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def query_spans(self, *, filtering: typing.Optional[FilteringInput] = OMIT, windowing: typing.Optional[Windowing] = OMIT, query_ref: typing.Optional[Reference] = OMIT, query_variant_ref: typing.Optional[Reference] = OMIT, query_revision_ref: typing.Optional[Reference] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SpansResponse]:
        """
        Parameters
        ----------
        filtering : typing.Optional[FilteringInput]
        
        windowing : typing.Optional[Windowing]
        
        query_ref : typing.Optional[Reference]
        
        query_variant_ref : typing.Optional[Reference]
        
        query_revision_ref : typing.Optional[Reference]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SpansResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "spans/query",method="POST",
            json={
                "filtering": convert_and_respect_annotation_metadata(object_=filtering, annotation=typing.Optional[FilteringInput], direction="write"),
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
                "query_ref": convert_and_respect_annotation_metadata(object_=query_ref, annotation=typing.Optional[Reference], direction="write"),
                "query_variant_ref": convert_and_respect_annotation_metadata(object_=query_variant_ref, annotation=typing.Optional[Reference], direction="write"),
                "query_revision_ref": convert_and_respect_annotation_metadata(object_=query_revision_ref, annotation=typing.Optional[Reference], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SpansResponse,
                    parse_obj_as(
                        type_ =SpansResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def query_spans_analytics(self, *, focus: typing.Optional[Focus] = None, format: typing.Optional[Format] = None, oldest: typing.Optional[QuerySpansAnalyticsRequestOldest] = None, newest: typing.Optional[QuerySpansAnalyticsRequestNewest] = None, interval: typing.Optional[int] = None, rate: typing.Optional[float] = None, filter: typing.Optional[str] = None, specs: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[AnalyticsResponse]:
        """
        Parameters
        ----------
        focus : typing.Optional[Focus]
        
        format : typing.Optional[Format]
        
        oldest : typing.Optional[QuerySpansAnalyticsRequestOldest]
        
        newest : typing.Optional[QuerySpansAnalyticsRequestNewest]
        
        interval : typing.Optional[int]
        
        rate : typing.Optional[float]
        
        filter : typing.Optional[str]
        
        specs : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[AnalyticsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "spans/analytics/query",method="POST",
            params={"focus": focus, "format": format, "oldest": oldest, "newest": newest, "interval": interval, "rate": rate, "filter": filter, "specs": specs, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AnalyticsResponse,
                    parse_obj_as(
                        type_ =AnalyticsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def query_spans_sessions(self, *, realtime: typing.Optional[bool] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SessionIdsResponse]:
        """
        Parameters
        ----------
        realtime : typing.Optional[bool]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SessionIdsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "spans/sessions/query",method="POST",
            json={
                "realtime": realtime,
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SessionIdsResponse,
                    parse_obj_as(
                        type_ =SessionIdsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def query_spans_users(self, *, realtime: typing.Optional[bool] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[UserIdsResponse]:
        """
        Parameters
        ----------
        realtime : typing.Optional[bool]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[UserIdsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "spans/users/query",method="POST",
            json={
                "realtime": realtime,
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UserIdsResponse,
                    parse_obj_as(
                        type_ =UserIdsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def fetch_span(self, trace_id: str, span_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SpanResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        span_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SpanResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"spans/{jsonable_encoder(trace_id)}/{jsonable_encoder(span_id)}",method="GET",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SpanResponse,
                    parse_obj_as(
                        type_ =SpanResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def create_simple_trace(self, *, trace: SimpleTraceCreate, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SimpleTraceResponse]:
        """
        Parameters
        ----------
        trace : SimpleTraceCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SimpleTraceResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "simple/traces/",method="POST",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=SimpleTraceCreate, direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTraceResponse,
                    parse_obj_as(
                        type_ =SimpleTraceResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def fetch_simple_trace(self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SimpleTraceResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SimpleTraceResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"simple/traces/{jsonable_encoder(trace_id)}",method="GET",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTraceResponse,
                    parse_obj_as(
                        type_ =SimpleTraceResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def delete_simple_trace(self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SimpleTraceLinkResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SimpleTraceLinkResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"simple/traces/{jsonable_encoder(trace_id)}",method="DELETE",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTraceLinkResponse,
                    parse_obj_as(
                        type_ =SimpleTraceLinkResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def edit_simple_trace(self, trace_id: str, *, trace: SimpleTraceEdit, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SimpleTraceResponse]:
        """
        Parameters
        ----------
        trace_id : str
        
        trace : SimpleTraceEdit
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SimpleTraceResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"simple/traces/{jsonable_encoder(trace_id)}",method="PATCH",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=SimpleTraceEdit, direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTraceResponse,
                    parse_obj_as(
                        type_ =SimpleTraceResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def query_simple_traces(self, *, trace: typing.Optional[SimpleTraceQuery] = OMIT, links: typing.Optional[typing.Sequence[OTelLinkInput]] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[SimpleTracesResponse]:
        """
        Parameters
        ----------
        trace : typing.Optional[SimpleTraceQuery]
        
        links : typing.Optional[typing.Sequence[OTelLinkInput]]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[SimpleTracesResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "simple/traces/query",method="POST",
            json={
                "trace": convert_and_respect_annotation_metadata(object_=trace, annotation=typing.Optional[SimpleTraceQuery], direction="write"),
                "links": convert_and_respect_annotation_metadata(object_=links, annotation=typing.Optional[typing.Sequence[OTelLinkInput]], direction="write"),
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimpleTracesResponse,
                    parse_obj_as(
                        type_ =SimpleTracesResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
