FROM node:20.18-slim

ENV TURBO_TELEMETRY_DISABLED=1

WORKDIR /app

# Install jq for JSON parsing
RUN apt-get update && apt-get install -y jq
    
# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
COPY ./entrypoint.sh /app/entrypoint.sh   

# Extract PNPM version and install it
RUN PNPM_VERSION=$(cat package.json | jq -r '.packageManager | split("@")[1]') && \
    npm install -g pnpm@${PNPM_VERSION}

COPY oss/package.json ./oss/yarn.lock* ./oss/package-lock.json* ./oss/pnpm-lock.yaml* ./oss/.npmrc* ./oss/
COPY ./pnpm-workspace.yaml ./turbo.json ./
# Copy patches directory before running pnpm i
COPY ./patches /app/patches/
RUN pnpm i

COPY tsconfig.json .

COPY oss/src ./oss/src
COPY oss/public ./oss/public
COPY oss/tsconfig.json ./oss

COPY oss/postcss.config.mjs ./oss/postcss.config.mjs

COPY oss/next.config.ts ./oss/next.config.ts

COPY oss/tailwind.config.ts ./oss/tailwind.config.ts

ENTRYPOINT ["./entrypoint.sh"]
EXPOSE 3000
