# This file was auto-generated by Fern from our API Definition.

import typing

CustomProviderKind = typing.Union[
    typing.Literal[
        "custom",
        "azure",
        "bedrock",
        "sagemaker",
        "vertex_ai",
        "openai",
        "cohere",
        "anyscale",
        "deepinfra",
        "alephalpha",
        "groq",
        "mistral",
        "mistralai",
        "anthropic",
        "perplexityai",
        "together_ai",
        "openrouter",
        "gemini",
    ],
    typing.Any,
]
