# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .o_tel_event_output import OTelEventOutput
from .o_tel_flat_span_output_end_time import OTelFlatSpanOutputEndTime
from .o_tel_flat_span_output_start_time import OTelFlatSpanOutputStartTime
from .o_tel_hash_output import OTelHashOutput
from .o_tel_link_output import OTelLinkOutput
from .o_tel_reference_output import OTelReferenceOutput
from .o_tel_span_kind import OTelSpanKind
from .o_tel_status_code import OTelStatusCode
from .span_type import SpanType
from .trace_type import TraceType


class OTelFlatSpanOutput(UniversalBaseModel):
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    deleted_at: typing.Optional[dt.datetime] = None
    created_by_id: typing.Optional[str] = None
    updated_by_id: typing.Optional[str] = None
    deleted_by_id: typing.Optional[str] = None
    trace_id: str
    span_id: str
    parent_id: typing.Optional[str] = None
    trace_type: typing.Optional[TraceType] = None
    span_type: typing.Optional[SpanType] = None
    span_kind: typing.Optional[OTelSpanKind] = None
    span_name: typing.Optional[str] = None
    start_time: typing.Optional[OTelFlatSpanOutputStartTime] = None
    end_time: typing.Optional[OTelFlatSpanOutputEndTime] = None
    status_code: typing.Optional[OTelStatusCode] = None
    status_message: typing.Optional[str] = None
    attributes: typing.Optional[typing.Dict[str, typing.Optional["FullJsonOutput"]]] = None
    references: typing.Optional[typing.List[OTelReferenceOutput]] = None
    links: typing.Optional[typing.List[OTelLinkOutput]] = None
    hashes: typing.Optional[typing.List[OTelHashOutput]] = None
    exception: typing.Optional[typing.Dict[str, typing.Optional["FullJsonOutput"]]] = None
    events: typing.Optional[typing.List[OTelEventOutput]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .full_json_output import FullJsonOutput  # noqa: E402, I001

update_forward_refs(OTelFlatSpanOutput, FullJsonOutput=FullJsonOutput)
