# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OrganizationDetails(UniversalBaseModel):
    id: str
    slug: typing.Optional[str] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    flags: typing.Optional[typing.Dict[str, typing.Any]] = None
    tags: typing.Optional[typing.Dict[str, typing.Any]] = None
    meta: typing.Optional[typing.Dict[str, typing.Any]] = None
    owner_id: str
    members: typing.Optional[typing.List[str]] = None
    invitations: typing.Optional[typing.List[typing.Any]] = None
    workspaces: typing.Optional[typing.List[str]] = None
    default_workspace: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
