# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .simple_evaluator_query_flags import SimpleEvaluatorQueryFlags


class SimpleEvaluatorQuery(UniversalBaseModel):
    flags: typing.Optional[SimpleEvaluatorQueryFlags] = None
    tags: typing.Optional[typing.Dict[str, typing.Optional["LabelJsonInput"]]] = None
    meta: typing.Optional[typing.Dict[str, typing.Optional["FullJsonInput"]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .label_json_input import LabelJsonInput  # noqa: E402, I001
from .full_json_input import FullJsonInput  # noqa: E402, I001

update_forward_refs(SimpleEvaluatorQuery, FullJsonInput=FullJsonInput, LabelJsonInput=LabelJsonInput)
