{{- if .Values.ingress.enabled }}
# Web frontend - no rewriting needed
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agenta-oss.fullname" . }}-web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "agenta-oss.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | default "agenta.local" }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
    {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "agenta-oss.fullname" . }}-web
            port:
              number: 3000
{{- end }}