"""Public agent-tool configuration and resolution API."""

from .compat import (
    ToolConfigDiagnostic,
    ToolConfigParseResult,
    coerce_tool_config,
    coerce_tool_configs,
)
from .errors import (
    DuplicateToolNameError,
    GatewayToolResolutionError,
    MissingToolSecretError,
    ReservedToolNameError,
    ToolConfigError,
    ToolConfigurationError,
    ToolError,
    ToolResolutionError,
    UnknownPlatformOpError,
    UnsupportedToolProviderError,
)
from .interfaces import (
    GatewayToolResolver,
    PlatformToolResolver,
    ToolSecretProvider,
    WorkflowToolResolver,
)
from .models import (
    BuiltinToolConfig,
    CallbackToolSpec,
    ClientToolConfig,
    ClientToolSpec,
    CodeToolConfig,
    CodeToolSpec,
    GatewayToolConfig,
    GatewayToolkitConfig,
    GatewayToolResolution,
    MissingSecretPolicy,
    PlatformToolConfig,
    ReferenceToolConfig,
    ResolvedToolSet,
    ToolCall,
    ToolCallback,
    ToolConfig,
    ToolConfigBase,
    ToolkitPolicy,
    ToolSpec,
)
from .parsing import parse_tool_config
from .resolver import EnvironmentToolSecretProvider, ToolResolver

__all__ = [
    "ToolConfigBase",
    "ToolConfig",
    "BuiltinToolConfig",
    "GatewayToolConfig",
    "GatewayToolkitConfig",
    "ToolkitPolicy",
    "CodeToolConfig",
    "ClientToolConfig",
    "ReferenceToolConfig",
    "PlatformToolConfig",
    "ToolSpec",
    "CallbackToolSpec",
    "CodeToolSpec",
    "ClientToolSpec",
    "ToolCall",
    "ToolCallback",
    "ResolvedToolSet",
    "GatewayToolResolution",
    "MissingSecretPolicy",
    "ToolResolver",
    "ToolSecretProvider",
    "GatewayToolResolver",
    "WorkflowToolResolver",
    "PlatformToolResolver",
    "EnvironmentToolSecretProvider",
    "parse_tool_config",
    "coerce_tool_config",
    "coerce_tool_configs",
    "ToolConfigDiagnostic",
    "ToolConfigParseResult",
    "ToolError",
    "ToolConfigError",
    "ToolConfigurationError",
    "ToolResolutionError",
    "GatewayToolResolutionError",
    "UnsupportedToolProviderError",
    "UnknownPlatformOpError",
    "MissingToolSecretError",
    "DuplicateToolNameError",
    "ReservedToolNameError",
]
