import os

from oss.src.utils.env import env

CLICKHOUSE_HOST = env.CLICKHOUSE_HOST
CLICKHOUSE_PORT = env.CLICKHOUSE_PORT
CLICKHOUSE_USER = env.CLICKHOUSE_USER
CLICKHOUSE_PASSWORD = env.CLICKHOUSE_PASSWORD
CLICKHOUSE_DATABASE = env.CLICKHOUSE_DATABASE
USE_CLICKHOUSE = env.USE_CLICKHOUSE
