supported_llm_models = {
    "Aleph Alpha": [
        "luminous-base",
        "luminous-base-control",
        "luminous-extended-control",
        "luminous-supreme",
    ],
    "Anthropic": [
        "anthropic/claude-3-5-sonnet-20240620",
        "anthropic/claude-3-opus-20240229",
        "anthropic/claude-3-sonnet-20240229",
        "anthropic/claude-3-haiku-20240307",
        "anthropic/claude-2.1",
        "anthropic/claude-2",
        "anthropic/claude-instant-1.2",
        "anthropic/claude-instant-1",
    ],
    "Anyscale": [
        "anyscale/meta-llama/Llama-2-13b-chat-hf",
        "anyscale/meta-llama/Llama-2-70b-chat-hf",
    ],
    "Cohere": [
        "cohere/command-light",
        "cohere/command-r-plus",
        "cohere/command-nightly",
    ],
    "DeepInfra": [
        "deepinfra/meta-llama/Llama-2-70b-chat-hf",
        "deepinfra/meta-llama/Llama-2-13b-chat-hf",
        "deepinfra/codellama/CodeLlama-34b-Instruct-hf",
        "deepinfra/mistralai/Mistral-7B-Instruct-v0.1",
        "deepinfra/jondurbin/airoboros-l2-70b-gpt4-1.4.1",
    ],
    "Gemini": [
        "gemini/gemini-1.5-pro-latest",
        "gemini/gemini-1.5-flash",
    ],
    "Groq": [
        "groq/deepseek-r1-distill-llama-70b",
        "groq/deepseek-r1-distill-llama-70b-specdec",
        "groq/distil-whisper-large-v3-en",
        "groq/gemma2-9b-it",
        "groq/llama-3.1-8b-instant",
        "groq/llama-3.2-11b-vision-preview",
        "groq/llama-3.2-1b-preview",
        "groq/llama-3.2-3b-preview",
        "groq/llama-3.2-90b-vision-preview",
        "groq/llama-3.3-70b-specdec",
        "groq/llama-3.3-70b-versatile",
        "groq/llama-guard-3-8b",
        "groq/llama3-70b-8192",
        "groq/llama3-8b-8192",
        "groq/mixtral-8x7b-32768",
        "groq/whisper-large-v3",
        "groq/whisper-large-v3-turbo",
    ],
    "Mistral": [
        "mistral/mistral-tiny",
        "mistral/mistral-small",
        "mistral/mistral-medium",
        "mistral/mistral-large-latest",
    ],
    "Open AI": [
        "gpt-3.5-turbo-1106",
        "gpt-3.5-turbo",
        "gpt-4",
        "gpt-4o",
        "gpt-4o-mini",
        "gpt-4-1106-preview",
    ],
    "OpenRouter": [
        "openrouter/anthropic/claude-3-opus",
        "openrouter/anthropic/claude-3-sonnet",
        "openrouter/anthropic/claude-3.5-haiku",
        "openrouter/anthropic/claude-3.5-haiku-20241022",
        "openrouter/anthropic/claude-3.5-haiku-20241022:beta",
        "openrouter/anthropic/claude-3.5-haiku:beta",
        "openrouter/anthropic/claude-3.5-sonnet",
        "openrouter/anthropic/claude-3.5-sonnet-20240620",
        "openrouter/anthropic/claude-3.5-sonnet-20240620:beta",
        "openrouter/anthropic/claude-3.5-sonnet:beta",
        "openrouter/anthropic/claude-instant-1.1",
        "openrouter/cohere/command",
        "openrouter/cohere/command-r",
        "openrouter/cohere/command-r-03-2024",
        "openrouter/cohere/command-r-08-2024",
        "openrouter/cohere/command-r-plus",
        "openrouter/cohere/command-r-plus-04-2024",
        "openrouter/cohere/command-r-plus-08-2024",
        "openrouter/cohere/command-r7b-12-2024",
        "openrouter/deepseek/deepseek-chat",
        "openrouter/deepseek/deepseek-chat-v2.5",
        "openrouter/deepseek/deepseek-coder",
        "openrouter/deepseek/deepseek-r1",
        "openrouter/deepseek/deepseek-r1-distill-llama-70b",
        "openrouter/deepseek/deepseek-r1-distill-qwen-1.5b",
        "openrouter/deepseek/deepseek-r1-distill-qwen-14b",
        "openrouter/deepseek/deepseek-r1-distill-qwen-32b",
        "openrouter/databricks/dbrx-instruct",
        "openrouter/google/gemini-2.0-flash-001",
        "openrouter/google/gemini-2.0-flash-exp:free",
        "openrouter/google/gemini-2.0-flash-lite-preview-02-05:free",
        "openrouter/google/gemini-2.0-flash-thinking-exp-1219:free",
        "openrouter/google/gemini-2.0-flash-thinking-exp:free",
        "openrouter/google/gemini-2.0-pro-exp-02-05:free",
        "openrouter/google/gemini-exp-1114",
        "openrouter/google/gemini-exp-1121",
        "openrouter/google/gemini-exp-1206:free",
        "openrouter/google/gemini-flash-1.5",
        "openrouter/google/gemini-flash-1.5-8b",
        "openrouter/google/gemini-flash-1.5-8b-exp",
        "openrouter/google/gemini-flash-1.5-exp",
        "openrouter/google/gemini-pro",
        "openrouter/google/gemini-pro-1.5",
        "openrouter/google/gemini-pro-1.5-exp",
        "openrouter/google/gemini-pro-vision",
        "openrouter/google/palm-2-chat-bison",
        "openrouter/google/palm-2-codechat-bison",
        "openrouter/meta-llama/llama-3.3-70b-instruct",
        "openrouter/meta-llama/llama-3.2-90b-vision-instruct",
        "openrouter/meta-llama/llama-3.1-405b-instruct",
        "openrouter/mistralai/mistral-large",
        "openrouter/mistralai/mistral-medium",
        "openrouter/mistralai/mistral-small",
        "openrouter/mistralai/mixtral-8x7b-instruct",
        "openrouter/nousresearch/hermes-3-llama-3.1-405b",
        "openrouter/nousresearch/hermes-3-llama-3.1-70b",
        "openrouter/nousresearch/nous-hermes-2-mixtral-8x7b-dpo",
        "openrouter/qwen/qwen-max",
        "openrouter/qwen/qwen-plus",
        "openrouter/qwen/qwen-2.5-72b-instruct",
        "openrouter/qwen/qwen-2.5-coder-32b-instruct",
        "openrouter/x-ai/grok-2",
        "openrouter/x-ai/grok-2-1212",
        "openrouter/x-ai/grok-2-mini",
        "openrouter/x-ai/grok-2-vision-1212",
        "openrouter/x-ai/grok-beta",
        "openrouter/x-ai/grok-vision-beta",
    ],
    "Perplexity AI": [
        "perplexity/sonar",
        "perplexity/sonar-pro",
        "perplexity/sonar-reasoning",
        "perplexity/sonar-reasoning-pro",
    ],
    "Together AI": [
        "together_ai/togethercomputer/llama-2-70b-chat",
        "together_ai/togethercomputer/llama-2-70b",
        "together_ai/togethercomputer/LLaMA-2-7B-32K",
        "together_ai/togethercomputer/Llama-2-7B-32K-Instruct",
        "together_ai/togethercomputer/llama-2-7b",
        "together_ai/togethercomputer/alpaca-7b",
        "together_ai/togethercomputer/CodeLlama-34b-Instruct",
        "together_ai/togethercomputer/CodeLlama-34b-Python",
        "together_ai/WizardLM/WizardCoder-Python-34B-V1.0",
        "together_ai/NousResearch/Nous-Hermes-Llama2-13b",
        "together_ai/Austism/chronos-hermes-13b",
    ],
}

providers_list = list(supported_llm_models.keys())

model_to_provider_mapping = {
    model: provider
    for provider, models in supported_llm_models.items()
    for model in models
}
