# This file was auto-generated by Fern from our API Definition.

import contextlib
import typing
from json.decoder import JSONDecodeError

from .. import core
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.archive_mount import ArchiveMount
from ..types.http_validation_error import HttpValidationError
from ..types.mount_credentials_response import MountCredentialsResponse
from ..types.mount_edit import MountEdit
from ..types.mount_file_deleted_response import MountFileDeletedResponse
from ..types.mount_file_written_response import MountFileWrittenResponse
from ..types.mount_folder_created_response import MountFolderCreatedResponse
from ..types.mount_query import MountQuery
from ..types.mount_response import MountResponse
from ..types.mounts_response import MountsResponse
from ..types.public_mount_create import PublicMountCreate
from ..types.windowing import Windowing
from .types.get_mount_files_request_order import GetMountFilesRequestOrder

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)
class RawMountsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
    
    def create_mount(self, *, mount: PublicMountCreate, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount : PublicMountCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "mounts/",method="POST",
            json={
                "mount": convert_and_respect_annotation_metadata(object_=mount, annotation=PublicMountCreate, direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def query_mounts(self, *, session_id: typing.Optional[str] = None, agent_id: typing.Optional[str] = None, include_archived: typing.Optional[bool] = None, mount: typing.Optional[MountQuery] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountsResponse]:
        """
        Parameters
        ----------
        session_id : typing.Optional[str]
        
        agent_id : typing.Optional[str]
        
        include_archived : typing.Optional[bool]
        
        mount : typing.Optional[MountQuery]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "mounts/query",method="POST",
            params={"session_id": session_id, "agent_id": agent_id, "include_archived": include_archived, }
            ,
            json={
                "mount": convert_and_respect_annotation_metadata(object_=mount, annotation=typing.Optional[MountQuery], direction="write"),
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountsResponse,
                    parse_obj_as(
                        type_ =MountsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def sign_agent_mount_credentials(self, *, artifact_id: str, name: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountCredentialsResponse]:
        """
        Parameters
        ----------
        artifact_id : str
        
        name : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountCredentialsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "mounts/agents/sign",method="POST",
            params={"artifact_id": artifact_id, "name": name, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountCredentialsResponse,
                    parse_obj_as(
                        type_ =MountCredentialsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def query_agent_mount(self, *, artifact_id: str, name: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountsResponse]:
        """
        Parameters
        ----------
        artifact_id : str
        
        name : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "mounts/agents/query",method="POST",
            json={
                "artifact_id": artifact_id,
                "name": name,
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountsResponse,
                    parse_obj_as(
                        type_ =MountsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def fetch_mount(self, mount_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}",method="GET",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def edit_mount(self, mount_id: str, *, mount: MountEdit, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        mount : MountEdit
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}",method="PUT",
            json={
                "mount": convert_and_respect_annotation_metadata(object_=mount, annotation=MountEdit, direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def sign_mount_credentials(self, mount_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountCredentialsResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountCredentialsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/sign",method="POST",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountCredentialsResponse,
                    parse_obj_as(
                        type_ =MountCredentialsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    @contextlib.contextmanager
    def export_mount_files(self, *, mounts: typing.Optional[typing.Sequence[ArchiveMount]] = OMIT, filename: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> typing.Iterator[HttpResponse[typing.Iterator[bytes]]]:
        """
        Parameters
        ----------
        mounts : typing.Optional[typing.Sequence[ArchiveMount]]
        
        filename : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.
        
        Returns
        -------
        typing.Iterator[HttpResponse[typing.Iterator[bytes]]]
            Successful Response
        """
        with self._client_wrapper.httpx_client.stream(
            "mounts/files/export",method="POST",
            json={
                "mounts": convert_and_respect_annotation_metadata(object_=mounts, annotation=typing.Sequence[ArchiveMount], direction="write"),
                "filename": filename,
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        ) as _response:
            def _stream() -> HttpResponse[typing.Iterator[bytes]]:
                try:
                    if 200 <= _response.status_code < 300:
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size)))
                    _response.read()
                    if _response.status_code == 422:
                        raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                            HttpValidationError,
                            parse_obj_as(
                                type_ =HttpValidationError,  # type: ignore
                                object_ =_response.json()
                            )
                        ))
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
            yield _stream()
    
    def archive_mount(self, mount_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/archive",method="POST",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def unarchive_mount(self, mount_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/unarchive",method="POST",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def create_mount_folder(self, mount_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountFolderCreatedResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountFolderCreatedResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files/folder",method="POST",
            params={"path": path, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountFolderCreatedResponse,
                    parse_obj_as(
                        type_ =MountFolderCreatedResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def upload_mount_file(self, mount_id: str, *, file: core.File, path: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountFileWrittenResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        file : core.File
            See core.File for more documentation
        
        path : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountFileWrittenResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files/upload",method="POST",
            params={"path": path, }
            ,
            data={
                }
            ,
            files={
                "file": file,
            }
            ,
            request_options=request_options,omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountFileWrittenResponse,
                    parse_obj_as(
                        type_ =MountFileWrittenResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    @contextlib.contextmanager
    def download_mount_file(self, mount_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Iterator[HttpResponse[typing.Iterator[bytes]]]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.
        
        Returns
        -------
        typing.Iterator[HttpResponse[typing.Iterator[bytes]]]
            Successful Response
        """
        with self._client_wrapper.httpx_client.stream(
            f"mounts/{jsonable_encoder(mount_id)}/files/download",method="GET",
            params={"path": path, }
            ,
            request_options=request_options,) as _response:
            def _stream() -> HttpResponse[typing.Iterator[bytes]]:
                try:
                    if 200 <= _response.status_code < 300:
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size)))
                    _response.read()
                    if _response.status_code == 422:
                        raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                            HttpValidationError,
                            parse_obj_as(
                                type_ =HttpValidationError,  # type: ignore
                                object_ =_response.json()
                            )
                        ))
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
            yield _stream()
    
    def get_mount_files(self, mount_id: str, *, path: typing.Optional[str] = None, read: typing.Optional[str] = None, order: typing.Optional[GetMountFilesRequestOrder] = None, limit: typing.Optional[int] = None, depth: typing.Optional[int] = None, with_counts: typing.Optional[bool] = None, git_aware: typing.Optional[bool] = None, include_gitignored: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[typing.Any]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : typing.Optional[str]
        
        read : typing.Optional[str]
        
        order : typing.Optional[GetMountFilesRequestOrder]
        
        limit : typing.Optional[int]
        
        depth : typing.Optional[int]
        
        with_counts : typing.Optional[bool]
        
        git_aware : typing.Optional[bool]
        
        include_gitignored : typing.Optional[bool]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files",method="GET",
            params={"path": path, "read": read, "order": order, "limit": limit, "depth": depth, "with_counts": with_counts, "git_aware": git_aware, "include_gitignored": include_gitignored, }
            ,
            request_options=request_options,)
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_ =typing.Any,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def write_mount_file(self, mount_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountFileWrittenResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountFileWrittenResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files",method="PUT",
            params={"path": path, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountFileWrittenResponse,
                    parse_obj_as(
                        type_ =MountFileWrittenResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    def delete_mount_file(self, mount_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[MountFileDeletedResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        HttpResponse[MountFileDeletedResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files",method="DELETE",
            params={"path": path, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountFileDeletedResponse,
                    parse_obj_as(
                        type_ =MountFileDeletedResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
class AsyncRawMountsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
    
    async def create_mount(self, *, mount: PublicMountCreate, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount : PublicMountCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "mounts/",method="POST",
            json={
                "mount": convert_and_respect_annotation_metadata(object_=mount, annotation=PublicMountCreate, direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def query_mounts(self, *, session_id: typing.Optional[str] = None, agent_id: typing.Optional[str] = None, include_archived: typing.Optional[bool] = None, mount: typing.Optional[MountQuery] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountsResponse]:
        """
        Parameters
        ----------
        session_id : typing.Optional[str]
        
        agent_id : typing.Optional[str]
        
        include_archived : typing.Optional[bool]
        
        mount : typing.Optional[MountQuery]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "mounts/query",method="POST",
            params={"session_id": session_id, "agent_id": agent_id, "include_archived": include_archived, }
            ,
            json={
                "mount": convert_and_respect_annotation_metadata(object_=mount, annotation=typing.Optional[MountQuery], direction="write"),
                "windowing": convert_and_respect_annotation_metadata(object_=windowing, annotation=typing.Optional[Windowing], direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountsResponse,
                    parse_obj_as(
                        type_ =MountsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def sign_agent_mount_credentials(self, *, artifact_id: str, name: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountCredentialsResponse]:
        """
        Parameters
        ----------
        artifact_id : str
        
        name : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountCredentialsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "mounts/agents/sign",method="POST",
            params={"artifact_id": artifact_id, "name": name, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountCredentialsResponse,
                    parse_obj_as(
                        type_ =MountCredentialsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def query_agent_mount(self, *, artifact_id: str, name: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountsResponse]:
        """
        Parameters
        ----------
        artifact_id : str
        
        name : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "mounts/agents/query",method="POST",
            json={
                "artifact_id": artifact_id,
                "name": name,
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountsResponse,
                    parse_obj_as(
                        type_ =MountsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def fetch_mount(self, mount_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}",method="GET",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def edit_mount(self, mount_id: str, *, mount: MountEdit, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        mount : MountEdit
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}",method="PUT",
            json={
                "mount": convert_and_respect_annotation_metadata(object_=mount, annotation=MountEdit, direction="write"),
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def sign_mount_credentials(self, mount_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountCredentialsResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountCredentialsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/sign",method="POST",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountCredentialsResponse,
                    parse_obj_as(
                        type_ =MountCredentialsResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    @contextlib.asynccontextmanager
    async def export_mount_files(self, *, mounts: typing.Optional[typing.Sequence[ArchiveMount]] = OMIT, filename: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[bytes]]]:
        """
        Parameters
        ----------
        mounts : typing.Optional[typing.Sequence[ArchiveMount]]
        
        filename : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.
        
        Returns
        -------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[bytes]]]
            Successful Response
        """
        async with self._client_wrapper.httpx_client.stream(
            "mounts/files/export",method="POST",
            json={
                "mounts": convert_and_respect_annotation_metadata(object_=mounts, annotation=typing.Sequence[ArchiveMount], direction="write"),
                "filename": filename,
            }
            ,
            headers={"content-type": "application/json", }
            ,
            request_options=request_options,omit=OMIT,
        ) as _response:
            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[bytes]]:
                try:
                    if 200 <= _response.status_code < 300:
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(response=_response, data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)))
                    await _response.aread()
                    if _response.status_code == 422:
                        raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                            HttpValidationError,
                            parse_obj_as(
                                type_ =HttpValidationError,  # type: ignore
                                object_ =_response.json()
                            )
                        ))
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
            yield await _stream()
    
    async def archive_mount(self, mount_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/archive",method="POST",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def unarchive_mount(self, mount_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/unarchive",method="POST",
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountResponse,
                    parse_obj_as(
                        type_ =MountResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def create_mount_folder(self, mount_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountFolderCreatedResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountFolderCreatedResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files/folder",method="POST",
            params={"path": path, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountFolderCreatedResponse,
                    parse_obj_as(
                        type_ =MountFolderCreatedResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def upload_mount_file(self, mount_id: str, *, file: core.File, path: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountFileWrittenResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        file : core.File
            See core.File for more documentation
        
        path : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountFileWrittenResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files/upload",method="POST",
            params={"path": path, }
            ,
            data={
                }
            ,
            files={
                "file": file,
            }
            ,
            request_options=request_options,omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountFileWrittenResponse,
                    parse_obj_as(
                        type_ =MountFileWrittenResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    @contextlib.asynccontextmanager
    async def download_mount_file(self, mount_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[bytes]]]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.
        
        Returns
        -------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[bytes]]]
            Successful Response
        """
        async with self._client_wrapper.httpx_client.stream(
            f"mounts/{jsonable_encoder(mount_id)}/files/download",method="GET",
            params={"path": path, }
            ,
            request_options=request_options,) as _response:
            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[bytes]]:
                try:
                    if 200 <= _response.status_code < 300:
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(response=_response, data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)))
                    await _response.aread()
                    if _response.status_code == 422:
                        raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                            HttpValidationError,
                            parse_obj_as(
                                type_ =HttpValidationError,  # type: ignore
                                object_ =_response.json()
                            )
                        ))
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
            yield await _stream()
    
    async def get_mount_files(self, mount_id: str, *, path: typing.Optional[str] = None, read: typing.Optional[str] = None, order: typing.Optional[GetMountFilesRequestOrder] = None, limit: typing.Optional[int] = None, depth: typing.Optional[int] = None, with_counts: typing.Optional[bool] = None, git_aware: typing.Optional[bool] = None, include_gitignored: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[typing.Any]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : typing.Optional[str]
        
        read : typing.Optional[str]
        
        order : typing.Optional[GetMountFilesRequestOrder]
        
        limit : typing.Optional[int]
        
        depth : typing.Optional[int]
        
        with_counts : typing.Optional[bool]
        
        git_aware : typing.Optional[bool]
        
        include_gitignored : typing.Optional[bool]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files",method="GET",
            params={"path": path, "read": read, "order": order, "limit": limit, "depth": depth, "with_counts": with_counts, "git_aware": git_aware, "include_gitignored": include_gitignored, }
            ,
            request_options=request_options,)
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_ =typing.Any,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def write_mount_file(self, mount_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountFileWrittenResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountFileWrittenResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files",method="PUT",
            params={"path": path, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountFileWrittenResponse,
                    parse_obj_as(
                        type_ =MountFileWrittenResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
    
    async def delete_mount_file(self, mount_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[MountFileDeletedResponse]:
        """
        Parameters
        ----------
        mount_id : str
        
        path : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AsyncHttpResponse[MountFileDeletedResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"mounts/{jsonable_encoder(mount_id)}/files",method="DELETE",
            params={"path": path, }
            ,
            request_options=request_options,)
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MountFileDeletedResponse,
                    parse_obj_as(
                        type_ =MountFileDeletedResponse,  # type: ignore
                        object_ =_response.json()
                    )
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(headers=dict(_response.headers), body=typing.cast(
                    HttpValidationError,
                    parse_obj_as(
                        type_ =HttpValidationError,  # type: ignore
                        object_ =_response.json()
                    )
                ))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
