# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mount import Mount
from .mount_credentials import MountCredentials


class MountCredentialsResponse(UniversalBaseModel):
    count: typing.Optional[int] = None
    mount: typing.Optional[Mount] = None
    credentials: typing.Optional[MountCredentials] = None
    
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:
        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
