/**
 * The icons the agent picker offers, grouped by what someone naming an agent would reach for.
 *
 * Curated rather than the full 1512-icon Phosphor set: the whole set is 12k lines of generated
 * path data, and a picker whose first screen is aircraft and alignment glyphs helps nobody. Adding
 * one is a one-line change plus `pnpm --filter @agenta/ui generate:icons`.
 *
 * Names are Phosphor's kebab-case ids. The generator fails loudly on any name that no longer
 * exists, so a Phosphor rename cannot silently drop an icon.
 */
export const CURATED_ICONS: readonly string[] = [
    // General — the default vocabulary for "what is this agent".
    "robot",
    "brain",
    "sparkle",
    "lightning",
    "rocket",
    "star",
    "heart",
    "flag",
    "crosshair",
    "compass",
    "lifebuoy",
    "bell",
    "bookmark",
    "tag",
    "eye",
    "shield",
    "target",
    "lightbulb",
    "magic-wand",
    "infinity",
    "check-circle",
    "warning",
    "question",
    "info",
    "house",
    "ghost",

    // Development
    "bug",
    "code",
    "terminal-window",
    "git-branch",
    "git-pull-request",
    "git-commit",
    "git-merge",
    "git-fork",
    "cpu",
    "hard-drives",
    "plug",
    "wrench",
    "hammer",
    "screwdriver",
    "gear",
    "package",
    "brackets-curly",
    "stack",
    "file-code",
    "keyboard",
    "circuitry",
    "brackets-square",

    // Data
    "chart-line",
    "chart-bar",
    "chart-pie-slice",
    "chart-donut",
    "chart-scatter",
    "database",
    "table",
    "funnel",
    "list-checks",
    "magnifying-glass",
    "tree-structure",
    "share-network",
    "cloud",
    "calculator",
    "percent",
    "gauge",
    "list-bullets",
    "sort-ascending",
    "diamonds-four",
    "binary",

    // Communication
    "envelope",
    "envelope-open",
    "chat-circle",
    "chats-circle",
    "megaphone",
    "phone",
    "paper-plane-tilt",
    "users",
    "user",
    "headphones",
    "microphone",
    "translate",
    "at",
    "bell-ringing",
    "broadcast",
    "rss",
    "share",
    "address-book",
    "hand-waving",

    // Business
    "briefcase",
    "buildings",
    "storefront",
    "shopping-cart",
    "currency-dollar",
    "receipt",
    "truck",
    "calendar-blank",
    "clock",
    "handshake",
    "presentation-chart",
    "coins",
    "bank",
    "credit-card",
    "trophy",
    "ticket",
    "scales",
    "gavel",
    "clipboard-text",
    "chart-line-up",

    // Science and health
    "flask",
    "test-tube",
    "atom",
    "dna",
    "microscope",
    "graduation-cap",
    "books",
    "math-operations",
    "thermometer",
    "first-aid-kit",
    "heartbeat",
    "pill",
    "virus",
    "planet",
    "magnet",
    "battery-charging",
    "recycle",

    // Media and design
    "camera",
    "image",
    "video-camera",
    "music-notes",
    "palette",
    "paint-brush",
    "film-slate",
    "pen-nib",
    "scissors",
    "ruler",
    "play",
    "pause",
    "speaker-high",
    "waveform",
    "crop",
    "frame-corners",
    "sticker",

    // Nature
    "plant",
    "leaf",
    "tree",
    "sun",
    "moon",
    "fire",
    "drop",
    "snowflake",
    "mountains",
    "globe",
    "wind",
    "paw-print",
    "cloud-sun",
    "umbrella",
    "waves",
    "bird",
    "flower",
    "cactus",
    "anchor",
] as const
