"""create project_invitations table

Revision ID: 9b0e1a740b88
Revises: 1c2d3e4f5a6b
Create Date: 2024-09-05 16:08:04.440845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b0e1a740b88"
down_revision: Union[str, None] = "1c2d3e4f5a6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get the current connection
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    if "project_invitations" not in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table(
            "project_invitations",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("token", sa.String(), nullable=False),
            sa.Column("email", sa.String(), nullable=False),
            sa.Column("used", sa.Boolean(), nullable=True),
            sa.Column("role", sa.String(), nullable=False),
            sa.Column("user_id", sa.UUID(), nullable=True),
            sa.Column("project_id", sa.UUID(), nullable=True),
            sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(
                ["project_id"],
                ["projects.id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("id"),
            sa.UniqueConstraint("token"),
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    if "project_invitations" in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table("project_invitations")
        # ### end Alembic commands ###
