# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.trigger_catalog_event_response import TriggerCatalogEventResponse
from ..types.trigger_catalog_events_response import TriggerCatalogEventsResponse
from ..types.trigger_catalog_integration_response import TriggerCatalogIntegrationResponse
from ..types.trigger_catalog_integrations_response import TriggerCatalogIntegrationsResponse
from ..types.trigger_catalog_provider_response import TriggerCatalogProviderResponse
from ..types.trigger_catalog_providers_response import TriggerCatalogProvidersResponse
from ..types.trigger_connection_create import TriggerConnectionCreate
from ..types.trigger_connection_response import TriggerConnectionResponse
from ..types.trigger_connections_response import TriggerConnectionsResponse
from ..types.trigger_deliveries_response import TriggerDeliveriesResponse
from ..types.trigger_delivery_query import TriggerDeliveryQuery
from ..types.trigger_delivery_response import TriggerDeliveryResponse
from ..types.trigger_event_ack import TriggerEventAck
from ..types.trigger_schedule_create import TriggerScheduleCreate
from ..types.trigger_schedule_edit import TriggerScheduleEdit
from ..types.trigger_schedule_query import TriggerScheduleQuery
from ..types.trigger_schedule_response import TriggerScheduleResponse
from ..types.trigger_schedules_response import TriggerSchedulesResponse
from ..types.trigger_subscription_create import TriggerSubscriptionCreate
from ..types.trigger_subscription_edit import TriggerSubscriptionEdit
from ..types.trigger_subscription_query import TriggerSubscriptionQuery
from ..types.trigger_subscription_response import TriggerSubscriptionResponse
from ..types.trigger_subscriptions_response import TriggerSubscriptionsResponse
from ..types.windowing import Windowing
from .raw_client import AsyncRawTriggersClient, RawTriggersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)
class TriggersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTriggersClient(client_wrapper=client_wrapper)
    
    @property
    def with_raw_response(self) -> RawTriggersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.
        
        Returns
        -------
        RawTriggersClient
        """
        return self._raw_client
    
    def ingest_composio_event(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerEventAck:
        """
        Receive a Composio provider event; verify, demux, ack-fast, enqueue.
        
        Public (no Agenta auth) — mirrors the Stripe events receiver. Scope and
        attribution are recovered downstream from the resolved subscription row.
        
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerEventAck
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.ingest_composio_event()
        """
        _response = self._raw_client.ingest_composio_event(request_options=request_options)
        return _response.data
    
    def list_trigger_providers(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogProvidersResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogProvidersResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.list_trigger_providers()
        """
        _response = self._raw_client.list_trigger_providers(request_options=request_options)
        return _response.data
    
    def fetch_trigger_provider(self, provider_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogProviderResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogProviderResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.fetch_trigger_provider(
            provider_key="provider_key",
        )
        """
        _response = self._raw_client.fetch_trigger_provider(provider_key, request_options=request_options)
        return _response.data
    
    def list_trigger_integrations(self, provider_key: str, *, search: typing.Optional[str] = None, sort_by: typing.Optional[str] = None, limit: typing.Optional[int] = None, cursor: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogIntegrationsResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        search : typing.Optional[str]
        
        sort_by : typing.Optional[str]
        
        limit : typing.Optional[int]
        
        cursor : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogIntegrationsResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.list_trigger_integrations(
            provider_key="provider_key",
        )
        """
        _response = self._raw_client.list_trigger_integrations(provider_key, search=search, sort_by=sort_by, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data
    
    def fetch_trigger_integration(self, provider_key: str, integration_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogIntegrationResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        integration_key : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogIntegrationResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.fetch_trigger_integration(
            provider_key="provider_key",
            integration_key="integration_key",
        )
        """
        _response = self._raw_client.fetch_trigger_integration(provider_key, integration_key, request_options=request_options)
        return _response.data
    
    def list_trigger_events(self, provider_key: str, integration_key: str, *, query: typing.Optional[str] = None, limit: typing.Optional[int] = None, cursor: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogEventsResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        integration_key : str
        
        query : typing.Optional[str]
        
        limit : typing.Optional[int]
        
        cursor : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogEventsResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.list_trigger_events(
            provider_key="provider_key",
            integration_key="integration_key",
        )
        """
        _response = self._raw_client.list_trigger_events(provider_key, integration_key, query=query, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data
    
    def fetch_trigger_event(self, provider_key: str, integration_key: str, event_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogEventResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        integration_key : str
        
        event_key : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogEventResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.fetch_trigger_event(
            provider_key="provider_key",
            integration_key="integration_key",
            event_key="event_key",
        )
        """
        _response = self._raw_client.fetch_trigger_event(provider_key, integration_key, event_key, request_options=request_options)
        return _response.data
    
    def query_trigger_connections(self, *, provider_key: typing.Optional[str] = None, integration_key: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionsResponse:
        """
        Parameters
        ----------
        provider_key : typing.Optional[str]
        
        integration_key : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionsResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.query_trigger_connections()
        """
        _response = self._raw_client.query_trigger_connections(provider_key=provider_key, integration_key=integration_key, request_options=request_options)
        return _response.data
    
    def create_trigger_connection(self, *, connection: TriggerConnectionCreate, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionResponse:
        """
        Parameters
        ----------
        connection : TriggerConnectionCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi, TriggerConnectionCreate
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.create_trigger_connection(
            connection=TriggerConnectionCreate(
                provider_key="composio",
                integration_key="integration_key",
            ),
        )
        """
        _response = self._raw_client.create_trigger_connection(connection=connection, request_options=request_options)
        return _response.data
    
    def fetch_trigger_connection(self, connection_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionResponse:
        """
        Parameters
        ----------
        connection_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.fetch_trigger_connection(
            connection_id="connection_id",
        )
        """
        _response = self._raw_client.fetch_trigger_connection(connection_id, request_options=request_options)
        return _response.data
    
    def delete_trigger_connection(self, connection_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        connection_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        None
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.delete_trigger_connection(
            connection_id="connection_id",
        )
        """
        _response = self._raw_client.delete_trigger_connection(connection_id, request_options=request_options)
        return _response.data
    
    def refresh_trigger_connection(self, connection_id: str, *, force: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionResponse:
        """
        Parameters
        ----------
        connection_id : str
        
        force : typing.Optional[bool]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.refresh_trigger_connection(
            connection_id="connection_id",
        )
        """
        _response = self._raw_client.refresh_trigger_connection(connection_id, force=force, request_options=request_options)
        return _response.data
    
    def revoke_trigger_connection(self, connection_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionResponse:
        """
        Parameters
        ----------
        connection_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.revoke_trigger_connection(
            connection_id="connection_id",
        )
        """
        _response = self._raw_client.revoke_trigger_connection(connection_id, request_options=request_options)
        return _response.data
    
    def list_trigger_subscriptions(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionsResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionsResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.list_trigger_subscriptions()
        """
        _response = self._raw_client.list_trigger_subscriptions(request_options=request_options)
        return _response.data
    
    def create_trigger_subscription(self, *, subscription: TriggerSubscriptionCreate, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription : TriggerSubscriptionCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi, TriggerSubscriptionCreate, TriggerSubscriptionData
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.create_trigger_subscription(
            subscription=TriggerSubscriptionCreate(
                connection_id="connection_id",
                data=TriggerSubscriptionData(
                    event_key="event_key",
                ),
            ),
        )
        """
        _response = self._raw_client.create_trigger_subscription(subscription=subscription, request_options=request_options)
        return _response.data
    
    def query_trigger_subscriptions(self, *, subscription: typing.Optional[TriggerSubscriptionQuery] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionsResponse:
        """
        Parameters
        ----------
        subscription : typing.Optional[TriggerSubscriptionQuery]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionsResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.query_trigger_subscriptions()
        """
        _response = self._raw_client.query_trigger_subscriptions(subscription=subscription, windowing=windowing, request_options=request_options)
        return _response.data
    
    def refresh_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.refresh_trigger_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.refresh_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    def revoke_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.revoke_trigger_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.revoke_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    def start_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.start_trigger_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.start_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    def stop_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.stop_trigger_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.stop_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    def fetch_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.fetch_trigger_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.fetch_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    def edit_trigger_subscription(self, subscription_id: str, *, subscription: TriggerSubscriptionEdit, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        subscription : TriggerSubscriptionEdit
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi, TriggerSubscriptionData, TriggerSubscriptionEdit
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.edit_trigger_subscription(
            subscription_id="subscription_id",
            subscription=TriggerSubscriptionEdit(
                connection_id="connection_id",
                data=TriggerSubscriptionData(
                    event_key="event_key",
                ),
            ),
        )
        """
        _response = self._raw_client.edit_trigger_subscription(subscription_id, subscription=subscription, request_options=request_options)
        return _response.data
    
    def delete_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        None
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.delete_trigger_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.delete_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    def list_trigger_schedules(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSchedulesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSchedulesResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.list_trigger_schedules()
        """
        _response = self._raw_client.list_trigger_schedules(request_options=request_options)
        return _response.data
    
    def create_trigger_schedule(self, *, schedule: TriggerScheduleCreate, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule : TriggerScheduleCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi, TriggerScheduleCreate, TriggerScheduleData
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.create_trigger_schedule(
            schedule=TriggerScheduleCreate(
                data=TriggerScheduleData(
                    event_key="event_key",
                    schedule="schedule",
                ),
            ),
        )
        """
        _response = self._raw_client.create_trigger_schedule(schedule=schedule, request_options=request_options)
        return _response.data
    
    def query_trigger_schedules(self, *, schedule: typing.Optional[TriggerScheduleQuery] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> TriggerSchedulesResponse:
        """
        Parameters
        ----------
        schedule : typing.Optional[TriggerScheduleQuery]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSchedulesResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.query_trigger_schedules()
        """
        _response = self._raw_client.query_trigger_schedules(schedule=schedule, windowing=windowing, request_options=request_options)
        return _response.data
    
    def fetch_trigger_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.fetch_trigger_schedule(
            schedule_id="schedule_id",
        )
        """
        _response = self._raw_client.fetch_trigger_schedule(schedule_id, request_options=request_options)
        return _response.data
    
    def edit_trigger_schedule(self, schedule_id: str, *, schedule: TriggerScheduleEdit, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
        
        schedule : TriggerScheduleEdit
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi, TriggerScheduleData, TriggerScheduleEdit
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.edit_trigger_schedule(
            schedule_id="schedule_id",
            schedule=TriggerScheduleEdit(
                data=TriggerScheduleData(
                    event_key="event_key",
                    schedule="schedule",
                ),
            ),
        )
        """
        _response = self._raw_client.edit_trigger_schedule(schedule_id, schedule=schedule, request_options=request_options)
        return _response.data
    
    def delete_trigger_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        schedule_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        None
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.delete_trigger_schedule(
            schedule_id="schedule_id",
        )
        """
        _response = self._raw_client.delete_trigger_schedule(schedule_id, request_options=request_options)
        return _response.data
    
    def start_trigger_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.start_trigger_schedule(
            schedule_id="schedule_id",
        )
        """
        _response = self._raw_client.start_trigger_schedule(schedule_id, request_options=request_options)
        return _response.data
    
    def stop_trigger_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.stop_trigger_schedule(
            schedule_id="schedule_id",
        )
        """
        _response = self._raw_client.stop_trigger_schedule(schedule_id, request_options=request_options)
        return _response.data
    
    def list_trigger_deliveries(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerDeliveriesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerDeliveriesResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.list_trigger_deliveries()
        """
        _response = self._raw_client.list_trigger_deliveries(request_options=request_options)
        return _response.data
    
    def query_trigger_deliveries(self, *, delivery: typing.Optional[TriggerDeliveryQuery] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> TriggerDeliveriesResponse:
        """
        Parameters
        ----------
        delivery : typing.Optional[TriggerDeliveryQuery]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerDeliveriesResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.query_trigger_deliveries()
        """
        _response = self._raw_client.query_trigger_deliveries(delivery=delivery, windowing=windowing, request_options=request_options)
        return _response.data
    
    def fetch_trigger_delivery(self, delivery_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerDeliveryResponse:
        """
        Parameters
        ----------
        delivery_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerDeliveryResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.triggers.fetch_trigger_delivery(
            delivery_id="delivery_id",
        )
        """
        _response = self._raw_client.fetch_trigger_delivery(delivery_id, request_options=request_options)
        return _response.data
class AsyncTriggersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTriggersClient(client_wrapper=client_wrapper)
    
    @property
    def with_raw_response(self) -> AsyncRawTriggersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.
        
        Returns
        -------
        AsyncRawTriggersClient
        """
        return self._raw_client
    
    async def ingest_composio_event(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerEventAck:
        """
        Receive a Composio provider event; verify, demux, ack-fast, enqueue.
        
        Public (no Agenta auth) — mirrors the Stripe events receiver. Scope and
        attribution are recovered downstream from the resolved subscription row.
        
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerEventAck
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.ingest_composio_event()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.ingest_composio_event(request_options=request_options)
        return _response.data
    
    async def list_trigger_providers(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogProvidersResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogProvidersResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.list_trigger_providers()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.list_trigger_providers(request_options=request_options)
        return _response.data
    
    async def fetch_trigger_provider(self, provider_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogProviderResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogProviderResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.fetch_trigger_provider(
                provider_key="provider_key",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_trigger_provider(provider_key, request_options=request_options)
        return _response.data
    
    async def list_trigger_integrations(self, provider_key: str, *, search: typing.Optional[str] = None, sort_by: typing.Optional[str] = None, limit: typing.Optional[int] = None, cursor: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogIntegrationsResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        search : typing.Optional[str]
        
        sort_by : typing.Optional[str]
        
        limit : typing.Optional[int]
        
        cursor : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogIntegrationsResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.list_trigger_integrations(
                provider_key="provider_key",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.list_trigger_integrations(provider_key, search=search, sort_by=sort_by, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data
    
    async def fetch_trigger_integration(self, provider_key: str, integration_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogIntegrationResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        integration_key : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogIntegrationResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.fetch_trigger_integration(
                provider_key="provider_key",
                integration_key="integration_key",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_trigger_integration(provider_key, integration_key, request_options=request_options)
        return _response.data
    
    async def list_trigger_events(self, provider_key: str, integration_key: str, *, query: typing.Optional[str] = None, limit: typing.Optional[int] = None, cursor: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogEventsResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        integration_key : str
        
        query : typing.Optional[str]
        
        limit : typing.Optional[int]
        
        cursor : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogEventsResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.list_trigger_events(
                provider_key="provider_key",
                integration_key="integration_key",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.list_trigger_events(provider_key, integration_key, query=query, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data
    
    async def fetch_trigger_event(self, provider_key: str, integration_key: str, event_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerCatalogEventResponse:
        """
        Parameters
        ----------
        provider_key : str
        
        integration_key : str
        
        event_key : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerCatalogEventResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.fetch_trigger_event(
                provider_key="provider_key",
                integration_key="integration_key",
                event_key="event_key",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_trigger_event(provider_key, integration_key, event_key, request_options=request_options)
        return _response.data
    
    async def query_trigger_connections(self, *, provider_key: typing.Optional[str] = None, integration_key: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionsResponse:
        """
        Parameters
        ----------
        provider_key : typing.Optional[str]
        
        integration_key : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionsResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.query_trigger_connections()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.query_trigger_connections(provider_key=provider_key, integration_key=integration_key, request_options=request_options)
        return _response.data
    
    async def create_trigger_connection(self, *, connection: TriggerConnectionCreate, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionResponse:
        """
        Parameters
        ----------
        connection : TriggerConnectionCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi, TriggerConnectionCreate
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.create_trigger_connection(
                connection=TriggerConnectionCreate(
                    provider_key="composio",
                    integration_key="integration_key",
                ),
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.create_trigger_connection(connection=connection, request_options=request_options)
        return _response.data
    
    async def fetch_trigger_connection(self, connection_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionResponse:
        """
        Parameters
        ----------
        connection_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.fetch_trigger_connection(
                connection_id="connection_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_trigger_connection(connection_id, request_options=request_options)
        return _response.data
    
    async def delete_trigger_connection(self, connection_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        connection_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        None
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.delete_trigger_connection(
                connection_id="connection_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.delete_trigger_connection(connection_id, request_options=request_options)
        return _response.data
    
    async def refresh_trigger_connection(self, connection_id: str, *, force: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionResponse:
        """
        Parameters
        ----------
        connection_id : str
        
        force : typing.Optional[bool]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.refresh_trigger_connection(
                connection_id="connection_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.refresh_trigger_connection(connection_id, force=force, request_options=request_options)
        return _response.data
    
    async def revoke_trigger_connection(self, connection_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerConnectionResponse:
        """
        Parameters
        ----------
        connection_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerConnectionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.revoke_trigger_connection(
                connection_id="connection_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_trigger_connection(connection_id, request_options=request_options)
        return _response.data
    
    async def list_trigger_subscriptions(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionsResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionsResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.list_trigger_subscriptions()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.list_trigger_subscriptions(request_options=request_options)
        return _response.data
    
    async def create_trigger_subscription(self, *, subscription: TriggerSubscriptionCreate, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription : TriggerSubscriptionCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import (
            AsyncAgentaApi,
            TriggerSubscriptionCreate,
            TriggerSubscriptionData,
        )
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.create_trigger_subscription(
                subscription=TriggerSubscriptionCreate(
                    connection_id="connection_id",
                    data=TriggerSubscriptionData(
                        event_key="event_key",
                    ),
                ),
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.create_trigger_subscription(subscription=subscription, request_options=request_options)
        return _response.data
    
    async def query_trigger_subscriptions(self, *, subscription: typing.Optional[TriggerSubscriptionQuery] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionsResponse:
        """
        Parameters
        ----------
        subscription : typing.Optional[TriggerSubscriptionQuery]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionsResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.query_trigger_subscriptions()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.query_trigger_subscriptions(subscription=subscription, windowing=windowing, request_options=request_options)
        return _response.data
    
    async def refresh_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.refresh_trigger_subscription(
                subscription_id="subscription_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.refresh_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    async def revoke_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.revoke_trigger_subscription(
                subscription_id="subscription_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    async def start_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.start_trigger_subscription(
                subscription_id="subscription_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.start_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    async def stop_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.stop_trigger_subscription(
                subscription_id="subscription_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.stop_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    async def fetch_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.fetch_trigger_subscription(
                subscription_id="subscription_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    async def edit_trigger_subscription(self, subscription_id: str, *, subscription: TriggerSubscriptionEdit, request_options: typing.Optional[RequestOptions] = None) -> TriggerSubscriptionResponse:
        """
        Parameters
        ----------
        subscription_id : str
        
        subscription : TriggerSubscriptionEdit
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSubscriptionResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import (
            AsyncAgentaApi,
            TriggerSubscriptionData,
            TriggerSubscriptionEdit,
        )
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.edit_trigger_subscription(
                subscription_id="subscription_id",
                subscription=TriggerSubscriptionEdit(
                    connection_id="connection_id",
                    data=TriggerSubscriptionData(
                        event_key="event_key",
                    ),
                ),
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.edit_trigger_subscription(subscription_id, subscription=subscription, request_options=request_options)
        return _response.data
    
    async def delete_trigger_subscription(self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        subscription_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        None
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.delete_trigger_subscription(
                subscription_id="subscription_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.delete_trigger_subscription(subscription_id, request_options=request_options)
        return _response.data
    
    async def list_trigger_schedules(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerSchedulesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSchedulesResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.list_trigger_schedules()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.list_trigger_schedules(request_options=request_options)
        return _response.data
    
    async def create_trigger_schedule(self, *, schedule: TriggerScheduleCreate, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule : TriggerScheduleCreate
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi, TriggerScheduleCreate, TriggerScheduleData
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.create_trigger_schedule(
                schedule=TriggerScheduleCreate(
                    data=TriggerScheduleData(
                        event_key="event_key",
                        schedule="schedule",
                    ),
                ),
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.create_trigger_schedule(schedule=schedule, request_options=request_options)
        return _response.data
    
    async def query_trigger_schedules(self, *, schedule: typing.Optional[TriggerScheduleQuery] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> TriggerSchedulesResponse:
        """
        Parameters
        ----------
        schedule : typing.Optional[TriggerScheduleQuery]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerSchedulesResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.query_trigger_schedules()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.query_trigger_schedules(schedule=schedule, windowing=windowing, request_options=request_options)
        return _response.data
    
    async def fetch_trigger_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.fetch_trigger_schedule(
                schedule_id="schedule_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_trigger_schedule(schedule_id, request_options=request_options)
        return _response.data
    
    async def edit_trigger_schedule(self, schedule_id: str, *, schedule: TriggerScheduleEdit, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
        
        schedule : TriggerScheduleEdit
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi, TriggerScheduleData, TriggerScheduleEdit
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.edit_trigger_schedule(
                schedule_id="schedule_id",
                schedule=TriggerScheduleEdit(
                    data=TriggerScheduleData(
                        event_key="event_key",
                        schedule="schedule",
                    ),
                ),
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.edit_trigger_schedule(schedule_id, schedule=schedule, request_options=request_options)
        return _response.data
    
    async def delete_trigger_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        schedule_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        None
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.delete_trigger_schedule(
                schedule_id="schedule_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.delete_trigger_schedule(schedule_id, request_options=request_options)
        return _response.data
    
    async def start_trigger_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.start_trigger_schedule(
                schedule_id="schedule_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.start_trigger_schedule(schedule_id, request_options=request_options)
        return _response.data
    
    async def stop_trigger_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerScheduleResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.stop_trigger_schedule(
                schedule_id="schedule_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.stop_trigger_schedule(schedule_id, request_options=request_options)
        return _response.data
    
    async def list_trigger_deliveries(self, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerDeliveriesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerDeliveriesResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.list_trigger_deliveries()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.list_trigger_deliveries(request_options=request_options)
        return _response.data
    
    async def query_trigger_deliveries(self, *, delivery: typing.Optional[TriggerDeliveryQuery] = OMIT, windowing: typing.Optional[Windowing] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> TriggerDeliveriesResponse:
        """
        Parameters
        ----------
        delivery : typing.Optional[TriggerDeliveryQuery]
        
        windowing : typing.Optional[Windowing]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerDeliveriesResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.query_trigger_deliveries()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.query_trigger_deliveries(delivery=delivery, windowing=windowing, request_options=request_options)
        return _response.data
    
    async def fetch_trigger_delivery(self, delivery_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerDeliveryResponse:
        """
        Parameters
        ----------
        delivery_id : str
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        TriggerDeliveryResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.triggers.fetch_trigger_delivery(
                delivery_id="delivery_id",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_trigger_delivery(delivery_id, request_options=request_options)
        return _response.data
