@host = http://localhost
@token = change-me
@base_url = {{host}}/api/preview/workflows

###
# @name create_account
POST {{host}}/api/admin/account
Content-Type: application/json
Authorization: Access {{token}}

###
@user_id = {{create_account.response.body.user.id}}
@authorization = {{create_account.response.body.scopes[0].credentials}}


###
# @name create_workflow
POST {{base_url}}/
Content-Type: application/json
Authorization: {{authorization}}

{
  "workflow": {
    "slug": "workflow-{{$guid}}",
    "name": "Workflow {{$guid}}",
    "description": "Workflow Description",
    "flags": {
      "is_custom": false,      
      "is_evaluator": false,
      "is_human": false
    },
    "tags": {
      "tag1": "value1",
      "tag2": "value2",
      "tag3": "value3"
    },
    "meta": {
      "meta1": "value1",
      "meta2": "value2",
      "meta3": "value3"
    }
  }
}

###
@workflow_id = {{create_workflow.response.body.workflow.id}}
@workflow_slug = {{create_workflow.response.body.workflow.slug}}

###
# @name fetch_workflow
GET {{base_url}}/{{workflow_id}}
Content-Type: application/json
Authorization: {{authorization}}

###
# @name edit_workflow
PUT {{base_url}}/{{workflow_id}}
Content-Type: application/json
Authorization: {{authorization}}

{
  "workflow": {
    "id": "{{workflow_id}}",
    "name": "Workflow 1 (updated)",
    "description": "Workflow description (updated)",
    "meta": {
      "key1": "tag 1",
      "key2": "tag 2",
      "key3": "tag 3"
    },
    "flags": {
      "is_custom": false,      
      "is_evaluator": false,
      "is_human": false
    }
  }
}

###
# @name archive_workflow_artifact
POST {{base_url}}/{{artifact_id}}/archive
Content-Type: application/json
Authorization: {{authorization}}

###
# @name unarchive_workflow_artifact
POST {{base_url}}/{{artifact_id}}/unarchive
Content-Type: application/json
Authorization: {{authorization}}

### query by artifact reference (id)
GET {{base_url}}/?artifact_ref={"id"="{{artifact_id}"}}
Content-Type: application/json
Authorization: {{authorization}}

### query by artifact reference (id)
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "artifact_ref": {
    "id": "{{artifact_id}}"
  }
}

### query by artifact reference (slug)
GET {{base_url}}/?artifact_ref={"slug"="{{artifact_slug}}"}
Content-Type: application/json
Authorization: {{authorization}}

### query by artifact reference (slug)
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "artifact_ref": {
    "slug": "{{artifact_slug}}"
  }
}

### query by artifact meta
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "artifact_meta": {
    "key3": "value"
  }
}

### query by artifact flags
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "artifact_flags": {
    "is_evaluator": true
  }
}

### query all (excluding archived)
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "include_archived": false
}

### query all including archived
POST {{base_url}}/query
Content-Type: application/json
Authorization: {{authorization}}

{
  "include_archived": true
}
