/** Copy for the guided first-agent flow. */
export const ONBOARDING_COPY = {
    pageTitle: "Get started",
    preparing: "Preparing your workspace",
    mintError: "Couldn't set up your agent.",
    retry: "Try again",
    stepCounter: (current: number, total: number) => `Step ${current} of ${total}`,
    back: "Back",
    continue: "Continue",
    /** Focus target for each step's heading; it needs no ring of its own. */
    headingClass: "m-0 text-2xl font-semibold leading-tight tracking-tight outline-none lg:text-3xl",
    role: {
        title: "What kind of work do you do?",
        subtitle: "We'll suggest agents that fit your work.",
    },
    referral: {
        title: "How did you hear about Agenta?",
        subtitle: "Pick the one that fits best.",
    },
    keyHint: (key: string) => `Press ${key}`,
    model: {
        title: "Choose how your agents run",
        subtitle: "Use your Agenta credits, or connect a plan you already pay for.",
        loadError: "Couldn't check your model connections",
        wallet: "Your wallet",
        ways: "Ways to pay",
        creditsTitle: "Agenta credits",
        creditsHint: "Ready to use on any model.",
        creditsBalance: (balance: string) => `${balance} credits left.`,
        creditsNone: "No Agenta credits on this workspace. Connect a plan or a key below.",
        chatgpt: "ChatGPT subscription",
        chatgptHint: "Run agents on your Plus or Pro plan.",
        chatgptReadyHint: "Agents can run on your ChatGPT plan.",
        chatgptDialogTitle: "Connect ChatGPT",
        chatgptDialogBody:
            "Sign in with your ChatGPT subscription. Your agent runs on it through the Codex harness.",
        chatgptConnected: "ChatGPT connected. Your agent will run on it.",
        key: "Your API key",
        keyHint: "OpenAI, Anthropic, Gemini and more.",
        keyUsing: (name: string, more: number) =>
            more > 0 ? `Using ${name} and ${more} more` : `Using ${name}`,
        connect: "Connect",
        addKey: "Add key",
        connected: "Connected",
        added: "Added",
        inUse: "In use",
        noneRunnable:
            "No model can run your agent yet. Connect ChatGPT or add an API key to continue.",
    },
    gallery: {
        title: "Create your first agent",
        subtitle: "Start blank or from a template. You can change everything before it's created.",
        recommended: "Recommended",
        all: "All",
        categories: "Template categories",
        scratch: "Start from scratch",
        scratchHint: "Blank agent",
        template: "Template",
        connects: "Connects",
        howItWorks: "How it works",
        when: "When",
        example: "Example run",
        review: "You'll review it before it's created.",
        use: "Use template",
        loading: "Loading templates",
        loadError: "Templates couldn't load",
        empty: "No templates in this category.",
    },
    creator: {
        title: "Create your agent",
        subtitle: "Give it a name, a look and something to do.",
        fromTemplateTitle: "Review your agent",
        fromTemplateSubtitle: (name: string) =>
            `Based on the ${name} template. Change anything you like.`,
        name: "Name",
        icon: "Icon and color",
        changeIcon: "Change agent icon",
        instructions: "Instructions",
        instructionsPlaceholder:
            "What should this agent do? e.g. Every Monday, summarize new deals and post the digest in #sales.",
        apps: "Apps",
        optional: "optional",
        appsHint: "Connect the apps your agent works in. Web search and a browser are included.",
        connecting: "Connecting",
        firstMessage: "First message",
        firstMessagePlaceholder: "What should it do first?",
        starters: "Message ideas",
        create: "Create agent",
        needsSomething: "Add instructions or a first message to create your agent.",
        modelMissing: "Your agent needs a model to run.",
        modelMissingAction: "Choose one",
        previewLabel: "Preview",
        previewAgent: "Agent",
        previewEmpty: "Tell your agent what to do and it will appear here.",
        previewComposer: (name: string) => `Message ${name}…`,
    },
} as const
