import type {OnboardingVariant} from "./onboardingChoices"
import type {OnboardingStep} from "./onboardingDraft"

/** Copy for the guided first-agent flow. */
export const ONBOARDING_COPY = {
    pageTitle: "Get started",
    preparing: "Preparing your workspace",
    mintError: "Couldn't set up your agent.",
    retry: "Try again",
    stepCounter: (current: number, total: number) => `Step ${current} of ${total}`,
    back: "Back",
    /** Focus target for each step's heading; it needs no ring of its own. */
    headingClass: "m-0 text-2xl font-semibold leading-tight outline-none",
    next: "Next",
    headings: {
        role: {
            title: "What will you be working on most?",
            subtitle: "We'll suggest agents that fit how you work.",
        },
        tools: {
            title: "What do you use every day?",
            subtitle: "Connect the apps your agents should work in.",
        },
        referral: {
            title: "How did you hear about Agenta?",
            subtitle: "One pick is enough.",
        },
    } satisfies Partial<Record<OnboardingStep, {title: string; subtitle: string}>>,
    tools: {
        search: "Search apps (at least 3 characters)",
        searchLabel: "Search tools",
        loadingMore: "Loading more apps",
        loadError: "Tools couldn't load",
        loadErrorHint: "You can continue and connect them later.",
        empty: "No apps found.",
        connect: "Connect",
        connecting: "Connecting",
        connected: "Connected",
    },
    model: {
        creditsTitle: "You're set with Agenta credits",
        creditsSubtitle: "Use them to try the platform. No card needed.",
        title: "Choose how to run your agent",
        subtitle: "Bring your subscription, or connect a model provider.",
        checking: "Checking available models",
        loadError: "Couldn't check your model connections",
        creditsCard: "Agenta credits added to your account",
        creditsCardHint: "Enough to try your first agent. Top up later, or bring your own.",
        noneAvailable: "Connect ChatGPT or add a provider key to run your first agent.",
        alternativesWithCredits: "Have a subscription? Use it instead",
        optional: "(optional)",
        alternatives: "Run it on your subscription or your own key",
        chatgpt: "ChatGPT",
        chatgptHint: "Plus · Pro · Team. Runs on the Codex harness.",
        chatgptDialogTitle: "Connect ChatGPT",
        chatgptDialogBody:
            "Sign in with your ChatGPT subscription. Your agent runs on it through the Codex harness.",
        chatgptConnected: "ChatGPT connected. Your agent will run on it.",
        claude: "Claude",
        claudeBadge: "Self-hosting only",
        claudeHint: "Pro · Max · Team. Runs on Claude Code.",
        docs: "Docs",
        byom: "Bring your own model",
        byomHint: "OpenAI, Anthropic, Gemini, Ollama, OpenRouter and more",
        byomUsing: (name: string, more: number) =>
            more > 0 ? `Using ${name} and ${more} more` : `Using ${name}`,
        addKey: "Add API key",
        connect: "Connect",
        connected: "Connected",
        nextWithCredits: "Continue with credits",
        nextWithChatgpt: "Continue with ChatGPT",
        nextWithKey: "Continue with your key",
    },
    agent: {
        title: (variant: OnboardingVariant) =>
            variant === "control" ? "Create your first agent" : "What would you like done first?",
        nameLabel: "Name",
        namePlaceholder: "New agent",
        create: (variant: OnboardingVariant) =>
            variant === "control" ? "Get started" : "Set up this agent",
        suggestionsFor: (role: string) => `Suggestions for ${role}`,
        suggestionsLoading: "Loading suggestions",
        suggestionsError: "Suggestions couldn't load",
        taskSubtitle: "Pick a task and see what you'll get. We'll build the agent for it.",
        recommended: "Recommended",
        somethingElse: "Something else",
        somethingElseHint: "Describe it in your own words.",
        taskLabel: "What would you like it to do?",
        previewLabel: "Agent we'll create",
        previewEmptyName: "No task picked",
        previewEmptyHint: "Pick a task to preview the agent and an example run.",
        exampleTitle: "Example run",
        exampleHint: "Illustration only. Your agent hasn't run yet.",
        iconLabel: (name: string) => `Agent icon ${name}`,
        colorLabel: (color: string) => `Agent color ${color}`,
        modelMissing: "Your agent needs a model to run.",
        modelMissingAction: "Choose one",
    },
} as const
