/** Copy for the guided first-agent flow. */
export const ONBOARDING_COPY = {
    pageTitle: "Get started",
    preparing: "Preparing your workspace",
    mintError: "Couldn't set up your agent.",
    stepCounter: (current: number, total: number) => `Step ${current} of ${total}`,
    continue: "Continue",
    /** The fixed steps' dot labels; a question's comes from its registry entry. */
    dots: {
        credits: "Credits",
        templates: "First agent",
    },
    /** Focus target for each step's heading; it needs no ring of its own. */
    headingClass:
        "m-0 text-[34px] font-semibold leading-10 tracking-[-0.02em] text-balance outline-none",
    kickerClass:
        "text-muted-foreground text-[11px] font-medium uppercase leading-4 tracking-[0.04em]",
    keyHint: (key: string) => `Press ${key}`,
    model: {
        kicker: "Added to your wallet",
        title: (credits: string) => `${credits} credits, on us`,
        subtitle: (usd: string) =>
            `That’s ${usd} to spend on any model. You can also connect your own plan below, or skip and do it later.`,
        creditsOnlyTitle: "Agenta credits, on us",
        creditsOnlySubtitle:
            "Run your first agents on Agenta’s models. You can also connect your own plan below, or skip and do it later.",
        noCreditsKicker: "Ways to pay",
        noCreditsTitle: "Choose how your agents run",
        noCreditsSubtitle: "Connect a plan you already pay for, or bring your own API key.",
        wallet: "Your wallet",
        ways: "Ways to pay",
        loadError: "Couldn't check your model connections",
        creditsTitle: "Agenta credits",
        creditsHint: "Ready to use on any model.",
        chatgpt: "ChatGPT subscription",
        chatgptHint: "Run agents on your Plus or Pro plan.",
        chatgptReadyHint: "Agents can run on your ChatGPT plan.",
        chatgptDialogTitle: "Connect ChatGPT",
        chatgptDialogBody:
            "Sign in with your ChatGPT subscription. Your agent runs on it through the Codex harness.",
        chatgptConnected: "ChatGPT connected. Your agent will run on it.",
        key: "Your API key",
        keyHint: (more: number) => `OpenAI, Anthropic, Gemini and ${more} more.`,
        keySaved: "Saved securely. You can use it on any agent.",
        keyTag: (provider: string, last4: string) => `${provider} ••••${last4}`,
        keyLabel: "API key",
        keyProvider: "Provider",
        keyProviders: (count: number) => `${count} providers`,
        keySearch: "Search providers",
        keyNoMatch: "No providers match",
        keyMore: "More providers…",
        keyInvalid: "That doesn’t look like a valid key.",
        keySaveFailed: "Couldn’t save this key. Try again.",
        save: "Save",
        cancel: "Cancel",
        keyUsing: (name: string, more: number) =>
            more > 0 ? `Using ${name} and ${more} more.` : `Using ${name}.`,
        connect: "Connect",
        addKey: "Add key",
        connected: "Connected",
        added: "Added",
        inUse: "In use",
        noneRunnable:
            "No model can run your agent yet. Connect ChatGPT or add an API key to continue.",
    },
    gallery: {
        title: "Create your first agent",
        subtitle: "Start blank or from a template. You can change everything before it's created.",
        recommended: "Recommended",
        all: "All",
        categories: "Template categories",
        scratch: "New agent",
        scratchHint: "Start from scratch",
        backToTemplates: "Templates",
        template: "Template",
        connects: "Connects",
        connectedCount: (ready: number, total: number) => `${ready} of ${total} connected`,
        connected: "Connected",
        connect: "Connect",
        connectApp: (name: string) => `Connect ${name}`,
        howItWorks: "How it works",
        when: "When",
        step: (n: number, app: string | null) => (app ? `Step ${n} · ${app}` : `Step ${n}`),
        useHint: "Creates the agent and opens it.",
        use: "Use template",
        creating: "Creating agent",
        loading: "Loading templates",
        loadError: "Templates couldn't load",
        empty: "No templates in this category.",
    },
    creator: {
        name: "Name",
        namePlaceholder: "Name your agent",
        icon: "Icon and color",
        iconLabel: (name: string) => `Icon ${name}`,
        colorLabel: (color: string) => `Color ${color}`,
        hue: "Custom color",
        firstMessage: "First message",
        starters: "Message ideas",
        modelMissing: "Your agent needs a model to run.",
        modelMissingAction: "Choose one",
    },
} as const
