apiVersion: v1
kind: Secret
metadata:
  name: agenta-secret
  namespace: agenta-oss
type: Opaque
data:
  AGENTA_AUTH_KEY: cmVwbGFjZS1tZQ==
  AGENTA_CRYPT_KEY: cmVwbGFjZS1tZQ==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
  POSTHOG_API_KEY: cGhjX2htVlN4SWpUVzFSRUJIWGdqMmF3NEhXOVg2Q1hiNkZ6ZXJCZ1A5WGVuQzc=
  SUPERTOKENS_API_KEY: ""
  GOOGLE_OAUTH_CLIENT_ID: ""
  GOOGLE_OAUTH_CLIENT_SECRET: ""
  GITHUB_OAUTH_CLIENT_ID: ""
  GITHUB_OAUTH_CLIENT_SECRET: ""
  NEW_RELIC_LICENSE_KEY: ""
  NRIA_LICENSE_KEY: ""
  LOOPS_API_KEY: ""
  SENDGRID_API_KEY: ""
  CRISP_WEBSITE_ID: ""
  STRIPE_API_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  ALEPHALPHA_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  ANYSCALE_API_KEY: ""
  COHERE_API_KEY: ""
  DEEPINFRA_API_KEY: ""
  GEMINI_API_KEY: ""
  GROQ_API_KEY: ""
  MISTRAL_API_KEY: ""
  OPENAI_API_KEY: ""
  OPENROUTER_API_KEY: ""
  PERPLEXITYAI_API_KEY: ""
  TOGETHERAI_API_KEY: ""
