FROM python:3.11-slim-bookworm

WORKDIR /app

RUN pip install --upgrade pip \
    && pip install poetry

COPY ./pyproject.toml ./poetry.lock* /app/

RUN poetry config virtualenvs.create false
RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=cache,target=/root/.cache/pypoetry \
    poetry install --no-interaction --no-ansi

COPY ./oss /app/oss/
COPY ./entrypoints /app/entrypoints/

# Copy local SDK if present (synced by build.sh before docker build)
# Uses glob pattern sd[k] to avoid failure if sdk/ doesn't exist (for OSS users)
COPY ./sd[k] /app/sdk/

# PYTHONPATH includes /app/sdk - if local SDK exists it takes precedence over PyPI version
ENV PYTHONPATH=/app:/app/sdk

EXPOSE 80
