FROM python:3.11-slim-bookworm

WORKDIR /services

RUN pip install --upgrade pip \
    && pip install poetry

COPY ./pyproject.toml /services/

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

RUN groupadd --gid 10001 agenta && \
    useradd --uid 10001 --gid 10001 --shell /bin/false --create-home agenta

COPY --chown=agenta:agenta ./oss /services/oss/
COPY --chown=agenta:agenta ./entrypoints /services/entrypoints/

ENV PYTHONPATH=/sdks/python:/clients/python:$PYTHONPATH

RUN echo "/clients/python" > /usr/local/lib/python3.11/site-packages/agenta_client_path.pth \
    && echo "/sdks/python" >> /usr/local/lib/python3.11/site-packages/agenta_client_path.pth

USER 10001

EXPOSE 8080
