import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "reference/api/agenta-backend",
    },
    {
      type: "category",
      label: "Variants",
      link: {
        type: "doc",
        id: "reference/api/variants",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/add-variant-from-base-and-config",
          label: "Add Variant From Base And Config",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/mark-variant-as-hidden",
          label: "Remove Variant",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/get-variant",
          label: "Get Variant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-variant-parameters",
          label: "Update Variant Parameters",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/update-variant-url",
          label: "Update Variant Url",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-variant-revisions",
          label: "Get Variant Revisions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-variant-revision",
          label: "Get Variant Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/mark-variant-revision-as-hidden",
          label: "Remove Variant Revision",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/configs-add",
          label: "Configs Add",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-fetch",
          label: "Configs Fetch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-fork",
          label: "Configs Fork",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-commit",
          label: "Configs Commit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-deploy",
          label: "Configs Deploy",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-delete",
          label: "Configs Delete",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-list",
          label: "Configs List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-history",
          label: "Configs History",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Evaluations",
      link: {
        type: "doc",
        id: "reference/api/evaluations",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/fetch-evaluation-ids-evaluations-by-resource-get",
          label: "Fetch Evaluation Ids",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-evaluation",
          label: "Create Evaluation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-list-evaluations-evaluations-get",
          label: "Fetch List Evaluations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-evaluations",
          label: "Delete Evaluations",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluation-status",
          label: "Fetch Evaluation Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluation-results",
          label: "Fetch Evaluation Results",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluation-scenarios",
          label: "Fetch Evaluation Scenarios",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluation",
          label: "Fetch Evaluation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluation-scenarios-evaluations-evaluation-scenarios-comparison-results-get",
          label: "Fetch Evaluation Scenarios",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Evaluators",
      link: {
        type: "doc",
        id: "reference/api/evaluators",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/get-evaluators-endpoint-evaluators-get",
          label: "Get Evaluators Endpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/evaluator-data-map-evaluators-map-post",
          label: "Evaluator Data Map",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/evaluator-run-evaluators-evaluator-key-run-post",
          label: "Evaluator Run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-evaluator-configs-evaluators-configs-get",
          label: "Get Evaluator Configs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-new-evaluator-config-evaluators-configs-post",
          label: "Create New Evaluator Config",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-evaluator-config-evaluators-configs-evaluator-config-id-get",
          label: "Get Evaluator Config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-evaluator-config-evaluators-configs-evaluator-config-id-put",
          label: "Update Evaluator Config",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/delete-evaluator-config-evaluators-configs-evaluator-config-id-delete",
          label: "Delete Evaluator Config",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Apps",
      link: {
        type: "doc",
        id: "reference/api/apps",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/list-app-variants",
          label: "List App Variants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-variant-by-env",
          label: "Get Variant By Env",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-app",
          label: "Create App",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-apps",
          label: "List Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-app",
          label: "Update App",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/remove-app",
          label: "Remove App",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/add-variant-from-url",
          label: "Add Variant From Url Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/add-variant-from-key",
          label: "Add Variant From Key Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-environments",
          label: "List Environments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/environment-revisions",
          label: "List App Environment Revisions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Human-Evaluations",
      link: {
        type: "doc",
        id: "reference/api/human-evaluations",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/create-human-evaluation",
          label: "Create Human Evaluation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-list-human-evaluations-human-evaluations-get",
          label: "Fetch List Human Evaluations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-evaluations-human-evaluations-delete",
          label: "Delete Evaluations",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/fetch-human-evaluation-human-evaluations-evaluation-id-get",
          label: "Fetch Human Evaluation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-human-evaluation",
          label: "Update Human Evaluation",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/fetch-human-evaluation-scenarios",
          label: "Fetch Human Evaluation Scenarios",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-evaluation-scenario-router-human-evaluations-evaluation-id-evaluation-scenario-evaluation-scenario-id-evaluation-type-put",
          label: "Update Evaluation Scenario Router",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-evaluation-scenario-score-router-human-evaluations-evaluation-scenario-evaluation-scenario-id-score-get",
          label: "Get Evaluation Scenario Score Router",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-evaluation-scenario-score-router-human-evaluations-evaluation-scenario-evaluation-scenario-id-score-put",
          label: "Update Evaluation Scenario Score Router",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/fetch-results",
          label: "Fetch Results",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Testsets",
      link: {
        type: "doc",
        id: "reference/api/testsets",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/upload-file",
          label: "Upload File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/import-testset",
          label: "Import Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-testsets",
          label: "Get Testsets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-testset",
          label: "Create Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-testsets",
          label: "Delete Testsets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/update-testset",
          label: "Update Testset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-single-testset",
          label: "Get Single Testset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/list-testsets",
          label: "Query Testsets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-testset",
          label: "Create Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-testset",
          label: "Fetch Testset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-testset",
          label: "Edit Testset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-testset",
          label: "Archive Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-testset",
          label: "Unarchive Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-testsets",
          label: "Query Testsets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-testset-from-file",
          label: "Create Testset From File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/update-testset-from-file",
          label: "Update Testset From File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-testset-to-file",
          label: "Fetch Testset To File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-testcase",
          label: "Fetch Testcase",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Containers",
      link: {
        type: "doc",
        id: "reference/api/containers",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/container-templates",
          label: "Container Templates",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Environments",
      link: {
        type: "doc",
        id: "reference/api/environments",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/deploy-to-environment",
          label: "Deploy To Environment",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Observability",
      link: {
        type: "doc",
        id: "reference/api/observability",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/otlp-v-1-traces",
          label: "Receive /v1/traces via OTLP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/otlp-status",
          label: "Status of OTLP endpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/otlp-receiver",
          label: "Receive traces via OTLP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-traces",
          label:
            "Query traces, with optional grouping, windowing, filtering, and pagination.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-traces",
          label: "Delete traces",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/query-analytics",
          label:
            "Query analytics, with optional grouping, windowing, filtering.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-trace-by-id",
          label: "Fetch trace by ID.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Bases",
      link: {
        type: "doc",
        id: "reference/api/bases",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/list-bases",
          label: "List Bases",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Configs",
      link: {
        type: "doc",
        id: "reference/api/configs",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/get-config",
          label: "Get Config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-config-deployment-revision",
          label: "Get Config Deployment Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/revert-deployment-revision",
          label: "Revert Deployment Revision",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Admin",
      items: [
        {
          type: "doc",
          id: "reference/api/create-accounts",
          label: "Create Accounts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-account",
          label: "Create Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-create-portal",
          label: "Create Portal Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-create-checkout",
          label: "Create Checkout Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-switch-plans",
          label: "Switch Plans Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-cancel-subscription",
          label: "Cancel Subscription Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-report-usage",
          label: "Report Usage",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Organization",
      items: [
        {
          type: "doc",
          id: "reference/api/fetch-organization-details",
          label: "Fetch Organization Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/list-organizations",
          label: "List Organizations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/invite-user-to-workspace",
          label: "Invite User To Organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/resend-invitation",
          label: "Resend User Invitation To Organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/accept-invitation",
          label: "Accept Organization Invitation",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Billing",
      items: [
        {
          type: "doc",
          id: "reference/api/handle-events",
          label: "Handle Events",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-portal",
          label: "Create Portal User Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-checkout",
          label: "Create Checkout User Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-plans",
          label: "Fetch Plan User Route",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/switch-plans",
          label: "Switch Plans User Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-subscription",
          label: "Fetch Subscription User Route",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/cancel-plan",
          label: "Cancel Subscription User Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-usage",
          label: "Fetch Usage User Route",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/admin-create-portal",
          label: "Create Portal Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-create-checkout",
          label: "Create Checkout Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-switch-plans",
          label: "Switch Plans Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-cancel-subscription",
          label: "Cancel Subscription Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-report-usage",
          label: "Report Usage",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Access Control",
      items: [
        {
          type: "doc",
          id: "reference/api/verify-permissions",
          label: "Verify Permissions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Scopes",
      items: [
        {
          type: "doc",
          id: "reference/api/get-projects",
          label: "Get Projects",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Api Keys",
      items: [
        {
          type: "doc",
          id: "reference/api/list-api-keys",
          label: "List Api Keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-api-key",
          label: "Create Api Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-api-key",
          label: "Delete Api Key",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Workspace",
      items: [
        {
          type: "doc",
          id: "reference/api/get-workspace",
          label: "Get Workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-all-workspace-roles",
          label: "Get All Workspace Roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/remove-user-from-workspace",
          label: "Remove User From Workspace",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Tracing",
      items: [
        {
          type: "doc",
          id: "reference/api/edit-trace",
          label: "Edit Trace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/add-trace",
          label: "Add Trace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-trace",
          label: "Fetch Trace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/remove-trace",
          label: "Remove Trace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/ingest-spans",
          label: "Ingest Spans",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-spans",
          label: "Query Spans",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/ingest-spans-rpc",
          label: "Ingest Spans",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-spans-rpc",
          label: "Query Spans",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Evals",
      items: [
        {
          type: "doc",
          id: "reference/api/list-evaluators",
          label: "Query Evaluators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-evaluator",
          label: "Create Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluator",
          label: "Fetch Evaluator",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-evaluator",
          label: "Edit Evaluator",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-evaluator",
          label: "Archive Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-evaluator",
          label: "Unarchive Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-evaluators",
          label: "Query Evaluators",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-annotation",
          label: "Create Annotation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-annotation",
          label: "Fetch Annotation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-annotation",
          label: "Delete Annotation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/query-annotations",
          label: "Query Annotations",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Workflows",
      items: [
        {
          type: "doc",
          id: "reference/api/create-workflow",
          label: "Create Workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-workflows",
          label: "Query Workflows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-workflow",
          label: "Fetch Workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-workflow",
          label: "Edit Workflow",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-workflow",
          label: "Archive Workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-workflow",
          label: "Unarchive Workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-workflows",
          label: "Query Workflows",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-workflow-variant",
          label: "Create Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-workflow-variants",
          label: "Query Workflow Variants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-workflow-variant",
          label: "Fetch Workflow Variant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-workflow-variant",
          label: "Edit Workflow Variant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-workflow-variant",
          label: "Archive Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-workflow-variant",
          label: "Unarchive Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-workflow-variants",
          label: "Query Workflow Variants",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/commit-workflow-revision-by-variant-id",
          label: "Commit Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fork-workflow-variant",
          label: "Fork Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-workflow-revision",
          label: "Create Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-workflow-revisions",
          label: "Query Workflow Revisions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-workflow-revision",
          label: "Fetch Workflow Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-workflow-revision",
          label: "Edit Workflow Revision",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-workflow-revision-rpc",
          label: "Archive Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-workflow-revision-rpc",
          label: "Unarchive Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-workflow-revisions",
          label: "Query Workflow Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fork-workflow-variant-by-revision-id",
          label: "Fork Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/commit-workflow-revision",
          label: "Commit Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/log-workflow-revisions",
          label: "Log Workflow Revisions",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Vault",
      items: [
        {
          type: "doc",
          id: "reference/api/list-secrets",
          label: "List Secrets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-secret",
          label: "Create Secret",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/read-secret",
          label: "Read Secret",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-secret",
          label: "Update Secret",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/delete-secret",
          label: "Delete Secret",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "reference/api/get-own-org",
          label: "Get User Organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-organization",
          label: "Update Organization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/create-workspace",
          label: "Create Workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/update-workspace",
          label: "Update Workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-all-workspace-permissions",
          label: "Get All Workspace Permissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/assign-role-to-user",
          label: "Assign Role To User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unassign-role-from-user",
          label: "Unassign Role From User",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/health-check",
          label: "Health Check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-user-profile",
          label: "User Profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/reset-user-password",
          label: "Reset User Password",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
