import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "reference/api/agenta-api",
    },
    {
      type: "category",
      label: "Variants",
      link: {
        type: "doc",
        id: "reference/api/variants",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/add-variant-from-base-and-config",
          label: "Add Variant From Base And Config",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/mark-variant-as-hidden",
          label: "Remove Variant",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/get-variant",
          label: "Get Variant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-variant-parameters",
          label: "Update Variant Parameters",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/update-variant-url",
          label: "Update Variant Url",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-variant-revisions",
          label: "Get Variant Revisions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-variant-revision",
          label: "Get Variant Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/query-variant-revisions",
          label: "Query Variant Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/mark-variant-revision-as-hidden",
          label: "Remove Variant Revision",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/configs-add",
          label: "Configs Add",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-fetch",
          label: "Configs Fetch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-fork",
          label: "Configs Fork",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-query",
          label: "Configs Query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-commit",
          label: "Configs Commit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-deploy",
          label: "Configs Deploy",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-delete",
          label: "Configs Delete",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-list",
          label: "Configs List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/configs-history",
          label: "Configs History",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Evaluations",
      link: {
        type: "doc",
        id: "reference/api/evaluations",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/refresh-runs-admin-evaluations-runs-refresh-post",
          label: "Refresh Runs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-runs-preview-evaluations-runs-post",
          label: "Create Runs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-runs-preview-evaluations-runs-delete",
          label: "Delete Runs",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/edit-runs-preview-evaluations-runs-patch",
          label: "Edit Runs",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/query-runs-preview-evaluations-runs-query-post",
          label: "Query Runs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/close-runs-preview-evaluations-runs-close-post",
          label: "Close Runs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/open-runs-preview-evaluations-runs-open-post",
          label: "Open Runs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-run-preview-evaluations-runs-run-id-get",
          label: "Fetch Run",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-run-preview-evaluations-runs-run-id-patch",
          label: "Edit Run",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-run-preview-evaluations-runs-run-id-delete",
          label: "Delete Run",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/close-run-preview-evaluations-runs-run-id-close-post",
          label: "Close Run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/close-run-preview-evaluations-runs-run-id-close-status-post",
          label: "Close Run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/open-run-preview-evaluations-runs-run-id-open-post",
          label: "Open Run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-scenarios-preview-evaluations-scenarios-post",
          label: "Create Scenarios",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-scenarios-preview-evaluations-scenarios-delete",
          label: "Delete Scenarios",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/edit-scenarios-preview-evaluations-scenarios-patch",
          label: "Edit Scenarios",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/query-scenarios-preview-evaluations-scenarios-query-post",
          label: "Query Scenarios",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-scenario-preview-evaluations-scenarios-scenario-id-get",
          label: "Fetch Scenario",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-scenario-preview-evaluations-scenarios-scenario-id-patch",
          label: "Edit Scenario",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-scenario-preview-evaluations-scenarios-scenario-id-delete",
          label: "Delete Scenario",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/create-results-preview-evaluations-results-post",
          label: "Create Results",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-results-preview-evaluations-results-delete",
          label: "Delete Results",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/edit-results-preview-evaluations-results-patch",
          label: "Edit Results",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/query-results-preview-evaluations-results-query-post",
          label: "Query Results",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-result-preview-evaluations-results-result-id-get",
          label: "Fetch Result",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-result-preview-evaluations-results-result-id-patch",
          label: "Edit Result",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-result-preview-evaluations-results-result-id-delete",
          label: "Delete Result",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/refresh-metrics-preview-evaluations-metrics-refresh-post",
          label: "Refresh Metrics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-metrics-preview-evaluations-metrics-post",
          label: "Create Metrics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-metrics-preview-evaluations-metrics-delete",
          label: "Delete Metrics",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/edit-metrics-preview-evaluations-metrics-patch",
          label: "Edit Metrics",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/query-metrics-preview-evaluations-metrics-query-post",
          label: "Query Metrics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-queues-preview-evaluations-queues-post",
          label: "Create Queues",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-queues-preview-evaluations-queues-delete",
          label: "Delete Queues",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/edit-queues-preview-evaluations-queues-patch",
          label: "Edit Queues",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/query-queues-preview-evaluations-queues-query-post",
          label: "Query Queues",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-queue-preview-evaluations-queues-queue-id-get",
          label: "Fetch Queue",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-queue-preview-evaluations-queues-queue-id-patch",
          label: "Edit Queue",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-queue-preview-evaluations-queues-queue-id-delete",
          label: "Delete Queue",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/fetch-queue-scenarios-preview-evaluations-queues-queue-id-scenarios-get",
          label: "Fetch Queue Scenarios",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-evaluation-preview-simple-evaluations-post",
          label: "Create Evaluation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluation-preview-simple-evaluations-evaluation-id-get",
          label: "Fetch Evaluation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-evaluation-preview-simple-evaluations-evaluation-id-patch",
          label: "Edit Evaluation",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-evaluation-preview-simple-evaluations-evaluation-id-delete",
          label: "Delete Evaluation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/query-evaluations-preview-simple-evaluations-query-post",
          label: "Query Evaluations",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/start-simple-evaluation",
          label: "Start Evaluation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/stop-evaluation-preview-simple-evaluations-evaluation-id-stop-post",
          label: "Stop Evaluation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/close-evaluation-preview-simple-evaluations-evaluation-id-close-post",
          label: "Close Evaluation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/open-evaluation-preview-simple-evaluations-evaluation-id-open-post",
          label: "Open Evaluation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluation-ids-evaluations-by-resource-get",
          label: "Fetch Evaluation Ids",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluation-status",
          label: "Fetch Evaluation Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-legacy-evaluation-results",
          label: "Fetch Evaluation Results",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-legacy-evaluation-scenarios",
          label: "Fetch Evaluation Scenarios",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-legacy-evaluations",
          label: "Fetch List Evaluations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-legacy-evaluations",
          label: "Delete Evaluations",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/fetch-legacy-evaluation",
          label: "Fetch Evaluation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-legacy-evaluation-scenarios-comparison-results",
          label: "Fetch Evaluation Scenarios Comparison Results",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/start-evaluation",
          label: "Start Evaluation",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Evaluators",
      link: {
        type: "doc",
        id: "reference/api/evaluators",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/create-evaluator",
          label: "Create Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluator",
          label: "Fetch Evaluator",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-evaluator",
          label: "Edit Evaluator",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-evaluator",
          label: "Archive Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-evaluator",
          label: "Unarchive Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-evaluators",
          label: "Query Evaluators",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-evaluator-variant",
          label: "Create Evaluator Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluator-variant",
          label: "Fetch Evaluator Variant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-evaluator-variant",
          label: "Edit Evaluator Variant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-evaluator-variant",
          label: "Archive Evaluator Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-evaluator-variant",
          label: "Unarchive Evaluator Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-evaluator-variants",
          label: "Query Evaluator Variants",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fork-evaluator-variant",
          label: "Fork Evaluator Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/retrieve-evaluator-revision",
          label: "Retrieve Evaluator Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-evaluator-revision",
          label: "Create Evaluator Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-evaluator-revision",
          label: "Fetch Evaluator Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-evaluator-revision",
          label: "Edit Evaluator Revision",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-evaluator-revision",
          label: "Archive Evaluator Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-evaluator-revision",
          label: "Unarchive Evaluator Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-evaluator-revisions",
          label: "Query Evaluator Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/commit-evaluator-revision",
          label: "Commit Evaluator Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/log-evaluator-revisions",
          label: "Log Evaluator Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-simple-evaluator",
          label: "Create Simple Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-simple-evaluator",
          label: "Fetch Simple Evaluator",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-simple-evaluator",
          label: "Edit Simple Evaluator",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-simple-evaluator",
          label: "Archive Simple Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-simple-evaluator",
          label: "Unarchive Simple Evaluator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-simple-evaluators",
          label: "Query Simple Evaluators",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-evaluators-endpoint-evaluators-get",
          label: "Get Evaluators Endpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/evaluator-data-map-evaluators-map-post",
          label: "Evaluator Data Map",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/evaluator-run-evaluators-evaluator-key-run-post",
          label: "Evaluator Run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-evaluator-configs-evaluators-configs-get",
          label: "Get Evaluator Configs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-new-evaluator-config-evaluators-configs-post",
          label: "Create New Evaluator Config",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-evaluator-config-evaluators-configs-evaluator-config-id-get",
          label: "Get Evaluator Config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-evaluator-config-evaluators-configs-evaluator-config-id-put",
          label: "Update Evaluator Config",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/delete-evaluator-config-evaluators-configs-evaluator-config-id-delete",
          label: "Delete Evaluator Config",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Apps",
      link: {
        type: "doc",
        id: "reference/api/apps",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/list-app-variants",
          label: "List App Variants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-variant-by-env",
          label: "Get Variant By Env",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-app",
          label: "Create App",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-apps",
          label: "List Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/read-app",
          label: "Read App",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-app",
          label: "Update App",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/remove-app",
          label: "Remove App",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/add-variant-from-url",
          label: "Add Variant From Url Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/add-variant-from-key",
          label: "Add Variant From Key Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-environments",
          label: "List Environments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/environment-revisions",
          label: "List App Environment Revisions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Testsets",
      link: {
        type: "doc",
        id: "reference/api/testsets",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/create-testset",
          label: "Create Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-testset",
          label: "Fetch Testset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-testset",
          label: "Edit Testset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-testset",
          label: "Archive Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-testset",
          label: "Unarchive Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-testsets",
          label: "Query Testsets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-testset-variant",
          label: "Create Testset Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-testset-variant",
          label: "Fetch Testset Variant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-testset-variant",
          label: "Edit Testset Variant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-testset-variant",
          label: "Archive Testset Variant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-testset-variant",
          label: "Unarchive Testset Variant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/query-testset-variants",
          label: "Query Testset Variants",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/retrieve-testset-revision",
          label: "Retrieve Testset Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-testset-revision",
          label: "Create Testset Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-testset-revision",
          label: "Fetch Testset Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-testset-revision",
          label: "Edit Testset Revision",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-testset-revision",
          label: "Archive Testset Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-testset-revision",
          label: "Unarchive Testset Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-testset-revision-to-file",
          label: "Fetch Testset Revision To File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-testset-revisions",
          label: "Query Testset Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/commit-testset-revision",
          label: "Commit Testset Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/log-testset-revisions",
          label: "Log Testset Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-simple-testset",
          label: "Create Simple Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-simple-testset",
          label: "Fetch Simple Testset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-simple-testset",
          label: "Edit Simple Testset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-simple-testset",
          label: "Archive Simple Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-simple-testset",
          label: "Unarchive Simple Testset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-simple-testsets",
          label: "Query Simple Testsets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-simple-testset-from-file",
          label: "Create Simple Testset From File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/edit-simple-testset-from-file",
          label: "Edit Simple Testset From File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-simple-testset-to-file",
          label: "Fetch Simple Testset To File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/transfer-simple-testset",
          label: "Transfer Simple Testset",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Containers",
      link: {
        type: "doc",
        id: "reference/api/containers",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/container-templates",
          label: "Container Templates",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Environments",
      link: {
        type: "doc",
        id: "reference/api/environments",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/create-environment",
          label: "Create Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-environment",
          label: "Fetch Environment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-environment",
          label: "Edit Environment",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-environment",
          label: "Archive Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-environment",
          label: "Unarchive Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-environments",
          label: "Query Environments",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-environment-variant",
          label: "Create Environment Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-environment-variant",
          label: "Fetch Environment Variant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-environment-variant",
          label: "Edit Environment Variant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-environment-variant",
          label: "Archive Environment Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-environment-variant",
          label: "Unarchive Environment Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-environment-variants",
          label: "Query Environment Variants",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/retrieve-environment-revision",
          label: "Retrieve Environment Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-environment-revision",
          label: "Create Environment Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-environment-revision",
          label: "Fetch Environment Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-environment-revision",
          label: "Edit Environment Revision",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-environment-revision",
          label: "Archive Environment Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-environment-revision",
          label: "Unarchive Environment Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-environment-revisions",
          label: "Query Environment Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/commit-environment-revision",
          label: "Commit Environment Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/log-environment-revisions",
          label: "Log Environment Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-simple-environment",
          label: "Create Simple Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-simple-environment",
          label: "Fetch Simple Environment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-simple-environment",
          label: "Edit Simple Environment",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-simple-environment",
          label: "Archive Simple Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-simple-environment",
          label: "Unarchive Simple Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-simple-environments",
          label: "Query Simple Environments",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/guard-simple-environment",
          label: "Guard Simple Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unguard-simple-environment",
          label: "Unguard Simple Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/deploy-to-environment",
          label: "Deploy To Environment",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Observability",
      link: {
        type: "doc",
        id: "reference/api/observability",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/otlp-status",
          label: "Status check for OTLP",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/otlp-ingest",
          label: "Ingest traces via OTLP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/ingest-spans-rpc",
          label: "Ingest Spans",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-spans-rpc",
          label: "Query Spans",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-legacy-analytics",
          label: "Fetch Legacy Analytics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-analytics",
          label: "Fetch Analytics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-trace",
          label: "Create Trace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-trace",
          label: "Fetch Trace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-trace",
          label: "Edit Trace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/delete-trace",
          label: "Delete Trace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/list-sessions",
          label: "List Sessions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-users",
          label: "List Users",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Organizations",
      link: {
        type: "doc",
        id: "reference/api/organizations",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/list-domains-organizations-domains-get",
          label: "List Domains",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-domain-organizations-domains-post",
          label: "Create Domain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/verify-domain-organizations-domains-verify-post",
          label: "Verify Domain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/refresh-domain-token-organizations-domains-domain-id-refresh-post",
          label: "Refresh Domain Token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/reset-domain-organizations-domains-domain-id-reset-post",
          label: "Reset Domain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-domain-organizations-domains-domain-id-delete",
          label: "Delete Domain",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/list-providers-organizations-providers-get",
          label: "List Providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-provider-organizations-providers-post",
          label: "Create Provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/update-provider-organizations-providers-provider-id-patch",
          label: "Update Provider",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-provider-organizations-providers-provider-id-delete",
          label: "Delete Provider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/test-provider-organizations-providers-provider-id-test-post",
          label: "Test Provider",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Configs",
      link: {
        type: "doc",
        id: "reference/api/configs",
      },
      items: [
        {
          type: "doc",
          id: "reference/api/get-config",
          label: "Get Config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-config-deployment-revision",
          label: "Get Config Deployment Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/revert-deployment-revision",
          label: "Revert Deployment Revision",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Billing",
      items: [
        {
          type: "doc",
          id: "reference/api/handle-events",
          label: "Handle Events",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-portal",
          label: "Create Portal User Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-checkout",
          label: "Create Checkout User Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-plans",
          label: "Fetch Plan User Route",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/switch-plans",
          label: "Switch Plans User Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-subscription",
          label: "Fetch Subscription User Route",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/cancel-plan",
          label: "Cancel Subscription User Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-usage",
          label: "Fetch Usage User Route",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/admin-create-portal",
          label: "Create Portal Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-create-checkout",
          label: "Create Checkout Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-switch-plans",
          label: "Switch Plans Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-cancel-subscription",
          label: "Cancel Subscription Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-report-usage",
          label: "Report Usage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-flush-usage",
          label: "Flush Usage",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Admin",
      items: [
        {
          type: "doc",
          id: "reference/api/admin-create-portal",
          label: "Create Portal Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-create-checkout",
          label: "Create Checkout Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-switch-plans",
          label: "Switch Plans Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-cancel-subscription",
          label: "Cancel Subscription Admin Route",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-report-usage",
          label: "Report Usage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/admin-flush-usage",
          label: "Flush Usage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/refresh-runs-admin-evaluations-runs-refresh-post",
          label: "Refresh Runs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-accounts",
          label: "Create Accounts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-account",
          label: "Create Account",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Organization",
      items: [
        {
          type: "doc",
          id: "reference/api/fetch-organization-details",
          label: "Fetch Organization Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/list-organizations",
          label: "List Organizations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/invite-user-to-workspace",
          label: "Invite User To Organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/resend-invitation",
          label: "Resend User Invitation To Organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/accept-invitation",
          label: "Accept Organization Invitation",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Secrets",
      items: [
        {
          type: "doc",
          id: "reference/api/list-secrets",
          label: "List Secrets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-secret",
          label: "Create Secret",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/read-secret",
          label: "Read Secret",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-secret",
          label: "Update Secret",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/delete-secret",
          label: "Delete Secret",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Auth",
      items: [
        {
          type: "doc",
          id: "reference/api/discover-auth-discover-post",
          label: "Discover",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/check-organization-access-auth-access-get",
          label: "Check Organization Access",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-session-identities-auth-session-identities-patch",
          label: "Update Session Identities",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/sso-callback-redirect-auth-sso-callback-organization-slug-provider-slug-get",
          label: "Sso Callback Redirect",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Invocations",
      items: [
        {
          type: "doc",
          id: "reference/api/create-invocation",
          label: "Create Invocation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-invocation-by-trace-id",
          label: "Fetch Invocation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-invocation-by-trace-id",
          label: "Edit Invocation",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-invocation-by-trace-id",
          label: "Delete Invocation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/fetch-invocation",
          label: "Fetch Invocation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-invocation",
          label: "Edit Invocation",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-invocation",
          label: "Delete Invocation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/query-invocations",
          label: "Query Invocations",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Annotations",
      items: [
        {
          type: "doc",
          id: "reference/api/create-annotation",
          label: "Create Annotation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-annotation-by-trace-id",
          label: "Fetch Annotation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-annotation-by-trace-id",
          label: "Edit Annotation",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-annotation-by-trace-id",
          label: "Delete Annotation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/fetch-annotation",
          label: "Fetch Annotation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-annotation",
          label: "Edit Annotation",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-annotation",
          label: "Delete Annotation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/query-annotations",
          label: "Query Annotations",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Testcases",
      items: [
        {
          type: "doc",
          id: "reference/api/fetch-testcase-preview-testcases-testcase-id-get",
          label: "Fetch Testcase",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/query-testcases-preview-testcases-query-post",
          label: "Query Testcases",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Queries",
      items: [
        {
          type: "doc",
          id: "reference/api/create-query",
          label: "Create Query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-query",
          label: "Fetch Query",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-query",
          label: "Edit Query",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-query",
          label: "Archive Query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-query",
          label: "Unarchive Query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-queries",
          label: "Query Queries",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/retrieve-query-revision",
          label: "Retrieve Query Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-query-revision",
          label: "Create Query Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-query-revision",
          label: "Fetch Query Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-query-revision",
          label: "Edit Query Revision",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-query-revision",
          label: "Archive Query Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-query-revision",
          label: "Unarchive Query Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-query-revisions",
          label: "Query Query Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/commit-query-revision",
          label: "Commit Query Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/log-query-revisions",
          label: "Log Query Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-simple-query",
          label: "Create Simple Query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-simple-query",
          label: "Fetch Simple Query",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-simple-query",
          label: "Edit Simple Query",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-simple-query",
          label: "Archive Simple Query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-simple-query",
          label: "Unarchive Simple Query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-simple-queries",
          label: "Query Simple Queries",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Folders",
      items: [
        {
          type: "doc",
          id: "reference/api/create-folder",
          label: "Create Folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-folder",
          label: "Fetch Folder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-folder",
          label: "Edit Folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/delete-folder",
          label: "Delete Folder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/query-folders",
          label: "Query Folders",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Applications",
      items: [
        {
          type: "doc",
          id: "reference/api/create-application",
          label: "Create Application",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-application",
          label: "Fetch Application",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-application",
          label: "Edit Application",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-application",
          label: "Archive Application",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-application",
          label: "Unarchive Application",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-applications",
          label: "Query Applications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-application-variant",
          label: "Create Application Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-application-variant",
          label: "Fetch Application Variant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-application-variant",
          label: "Edit Application Variant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-application-variant",
          label: "Archive Application Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-application-variant",
          label: "Unarchive Application Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-application-variants",
          label: "Query Application Variants",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fork-application-variant",
          label: "Fork Application Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/retrieve-application-revision",
          label: "Retrieve Application Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-application-revision",
          label: "Create Application Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-application-revision",
          label: "Fetch Application Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-application-revision",
          label: "Edit Application Revision",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-application-revision",
          label: "Archive Application Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-application-revision",
          label: "Unarchive Application Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-application-revisions",
          label: "Query Application Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/commit-application-revision",
          label: "Commit Application Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/log-application-revisions",
          label: "Log Application Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-simple-application",
          label: "Create Simple Application",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-simple-applications",
          label: "Query Simple Applications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-simple-application",
          label: "Fetch Simple Application",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-simple-application",
          label: "Edit Simple Application",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-simple-application",
          label: "Archive Simple Application",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-simple-application",
          label: "Unarchive Simple Application",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Workflows",
      items: [
        {
          type: "doc",
          id: "reference/api/create-workflow",
          label: "Create Workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-workflow",
          label: "Fetch Workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-workflow",
          label: "Edit Workflow",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-workflow",
          label: "Archive Workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-workflow",
          label: "Unarchive Workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-workflows",
          label: "Query Workflows",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-workflow-variant",
          label: "Create Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-workflow-variant",
          label: "Fetch Workflow Variant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-workflow-variant",
          label: "Edit Workflow Variant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-workflow-variant",
          label: "Archive Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-workflow-variant",
          label: "Unarchive Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-workflow-variants",
          label: "Query Workflow Variants",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fork-workflow-variant",
          label: "Fork Workflow Variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/retrieve-workflow-revision",
          label: "Retrieve Workflow Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-workflow-revision",
          label: "Create Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/fetch-workflow-revision",
          label: "Fetch Workflow Revision",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/edit-workflow-revision",
          label: "Edit Workflow Revision",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/archive-workflow-revision-rpc",
          label: "Archive Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unarchive-workflow-revision-rpc",
          label: "Unarchive Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/query-workflow-revisions",
          label: "Query Workflow Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/commit-workflow-revision",
          label: "Commit Workflow Revision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/log-workflow-revisions",
          label: "Log Workflow Revisions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/invoke-workflow",
          label: "Invoke Workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/inspect-workflow",
          label: "Inspect Workflow",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Access Control",
      items: [
        {
          type: "doc",
          id: "reference/api/verify-permissions",
          label: "Verify Permissions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Scopes",
      items: [
        {
          type: "doc",
          id: "reference/api/get-projects",
          label: "Get Projects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-project",
          label: "Create Project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-project",
          label: "Get Project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-project",
          label: "Delete Project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/update-project",
          label: "Update Project",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Api Keys",
      items: [
        {
          type: "doc",
          id: "reference/api/list-api-keys",
          label: "List Api Keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-api-key",
          label: "Create Api Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/delete-api-key",
          label: "Delete Api Key",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Workspace",
      items: [
        {
          type: "doc",
          id: "reference/api/get-workspace",
          label: "Get Workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-all-workspace-roles",
          label: "Get All Workspace Roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/remove-user-from-workspace",
          label: "Remove User From Workspace",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "reference/api/patch-organization",
          label: "Update Organization",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/update-organization",
          label: "Update Organization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/delete-organization",
          label: "Delete Organization",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/create-workspace",
          label: "Create Workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/update-workspace",
          label: "Update Workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/transfer-organization-ownership",
          label: "Transfer Organization Ownership",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/create-organization",
          label: "Create Organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-organization-domains",
          label: "List Organization Domains",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-organization-domain",
          label: "Create Organization Domain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-organization-domain",
          label: "Get Organization Domain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-organization-domain",
          label: "Delete Organization Domain",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/verify-organization-domain",
          label: "Verify Organization Domain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-organization-providers",
          label: "List Organization Providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create-organization-provider",
          label: "Create Organization Provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-organization-provider",
          label: "Get Organization Provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-organization-provider",
          label: "Update Organization Provider",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/delete-organization-provider",
          label: "Delete Organization Provider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/get-all-workspace-permissions",
          label: "Get All Workspace Permissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/assign-role-to-user",
          label: "Assign Role To User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/unassign-role-from-user",
          label: "Unassign Role From User",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/health-check",
          label: "Health Check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/fetch-user-profile",
          label: "User Profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/update-user-username",
          label: "Update User Username",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/reset-user-password",
          label: "Reset User Password",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
