export const STATUS_COLOR: Record<string, string> = {
    success: "success",
    done: "success",
    failure: "error",
    failed: "error",
    EVALUATION_FAILED: "error",
    EVALUATION_FINISHED_WITH_ERRORS: "warning",
    cancelled: "warning",
    EVALUATION_AGGREGATION_FAILED: "warning",
    pending: "default",
    EVALUATION_INITIALIZED: "default",
    running: "blue",
    incomplete: "blue",
    EVALUATION_STARTED: "blue",
    revalidating: "purple",
}

export const STATUS_COLOR_TEXT: Record<string, string> = {
    success: "text-green-600",
    done: "text-green-600",
    failure: "text-red-500",
    failed: "text-red-500",
    EVALUATION_FAILED: "text-red-500",
    EVALUATION_FINISHED_WITH_ERRORS: "text-orange-500",
    cancelled: "text-yellow-500",
    EVALUATION_AGGREGATION_FAILED: "text-orange-500",
    pending: "text-gray-400",
    EVALUATION_INITIALIZED: "text-gray-400",
    running: "text-blue-500",
    EVALUATION_STARTED: "text-blue-500",
    revalidating: "text-purple-500",
}
