name: "00 - sync labels"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/.labels.yml"
      - ".github/workflows/00-sync-labels.yml"
  pull_request:
    paths:
      - ".github/.labels.yml"
      - ".github/workflows/00-sync-labels.yml"

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/.labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
          skip-delete: true
