# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .invoke_workflow_response import InvokeWorkflowResponse
    from .query_workflow_revisions_request_order import (
        QueryWorkflowRevisionsRequestOrder,
    )
    from .query_workflow_variants_request_order import QueryWorkflowVariantsRequestOrder
    from .query_workflows_request_order import QueryWorkflowsRequestOrder
_dynamic_imports: typing.Dict[str, str] = {
    "InvokeWorkflowResponse": ".invoke_workflow_response",
    "QueryWorkflowRevisionsRequestOrder": ".query_workflow_revisions_request_order",
    "QueryWorkflowVariantsRequestOrder": ".query_workflow_variants_request_order",
    "QueryWorkflowsRequestOrder": ".query_workflows_request_order",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "InvokeWorkflowResponse",
    "QueryWorkflowRevisionsRequestOrder",
    "QueryWorkflowVariantsRequestOrder",
    "QueryWorkflowsRequestOrder",
]
