#!/bin/sh

set -e

if [ "$AGENTA_LICENSE" != "ee" ]; then
  AGENTA_LICENSE="oss"
fi

if [ "$ENTRYPOINT_DIR" != "." ]; then
  ENTRYPOINT_DIR="/app"
fi

# Infer AGENTA_SENDGRID_ENABLED from SENDGRID_API_KEY and sender address
SENDGRID_FROM_ADDRESS_VALUE="${SENDGRID_FROM_ADDRESS:-${AGENTA_AUTHN_EMAIL_FROM:-${AGENTA_SEND_EMAIL_FROM_ADDRESS}}}"
if [ -n "$SENDGRID_API_KEY" ] && [ -n "$SENDGRID_FROM_ADDRESS_VALUE" ]; then
  export AGENTA_SENDGRID_ENABLED="true"
else
  export AGENTA_SENDGRID_ENABLED="false"
fi

# Infer AGENTA_TOOLS_ENABLED from COMPOSIO_API_KEY
if [ -n "$COMPOSIO_API_KEY" ]; then
  export AGENTA_TOOLS_ENABLED="true"
else
  export AGENTA_TOOLS_ENABLED="false"
fi

mkdir -p "${ENTRYPOINT_DIR}/${AGENTA_LICENSE}/public"

# Derive frontend auth feature flags
# First, check if OIDC providers are configured
AUTH_OIDC_ENABLED="false"
EFFECTIVE_GOOGLE_OAUTH_CLIENT_ID=""
if [ -n "${GOOGLE_OAUTH_CLIENT_ID}" ] && [ -n "${GOOGLE_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_GOOGLE_OAUTH_CLIENT_ID="${GOOGLE_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_GOOGLE_WORKSPACES_OAUTH_CLIENT_ID=""
if [ -n "${GOOGLE_WORKSPACES_OAUTH_CLIENT_ID}" ] && [ -n "${GOOGLE_WORKSPACES_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_GOOGLE_WORKSPACES_OAUTH_CLIENT_ID="${GOOGLE_WORKSPACES_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_GITHUB_OAUTH_CLIENT_ID=""
if [ -n "${GITHUB_OAUTH_CLIENT_ID}" ] && [ -n "${GITHUB_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_GITHUB_OAUTH_CLIENT_ID="${GITHUB_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_FACEBOOK_OAUTH_CLIENT_ID=""
if [ -n "${FACEBOOK_OAUTH_CLIENT_ID}" ] && [ -n "${FACEBOOK_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_FACEBOOK_OAUTH_CLIENT_ID="${FACEBOOK_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_APPLE_OAUTH_CLIENT_ID=""
if [ -n "${APPLE_OAUTH_CLIENT_ID}" ] && { [ -n "${APPLE_OAUTH_CLIENT_SECRET}" ] || { [ -n "${APPLE_KEY_ID}" ] && [ -n "${APPLE_TEAM_ID}" ] && [ -n "${APPLE_PRIVATE_KEY}" ]; }; }; then
  EFFECTIVE_APPLE_OAUTH_CLIENT_ID="${APPLE_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_DISCORD_OAUTH_CLIENT_ID=""
if [ -n "${DISCORD_OAUTH_CLIENT_ID}" ] && [ -n "${DISCORD_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_DISCORD_OAUTH_CLIENT_ID="${DISCORD_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_TWITTER_OAUTH_CLIENT_ID=""
if [ -n "${TWITTER_OAUTH_CLIENT_ID}" ] && [ -n "${TWITTER_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_TWITTER_OAUTH_CLIENT_ID="${TWITTER_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_GITLAB_OAUTH_CLIENT_ID=""
if [ -n "${GITLAB_OAUTH_CLIENT_ID}" ] && [ -n "${GITLAB_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_GITLAB_OAUTH_CLIENT_ID="${GITLAB_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_BITBUCKET_OAUTH_CLIENT_ID=""
if [ -n "${BITBUCKET_OAUTH_CLIENT_ID}" ] && [ -n "${BITBUCKET_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_BITBUCKET_OAUTH_CLIENT_ID="${BITBUCKET_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_LINKEDIN_OAUTH_CLIENT_ID=""
if [ -n "${LINKEDIN_OAUTH_CLIENT_ID}" ] && [ -n "${LINKEDIN_OAUTH_CLIENT_SECRET}" ]; then
  EFFECTIVE_LINKEDIN_OAUTH_CLIENT_ID="${LINKEDIN_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_OKTA_OAUTH_CLIENT_ID=""
if [ -n "${OKTA_OAUTH_CLIENT_ID}" ] && [ -n "${OKTA_OAUTH_CLIENT_SECRET}" ] && [ -n "${OKTA_DOMAIN}" ]; then
  EFFECTIVE_OKTA_OAUTH_CLIENT_ID="${OKTA_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_AZURE_AD_OAUTH_CLIENT_ID=""
AZURE_AD_OAUTH_CLIENT_ID_VALUE="${AZURE_AD_OAUTH_CLIENT_ID:-${ACTIVE_DIRECTORY_OAUTH_CLIENT_ID}}"
AZURE_AD_OAUTH_CLIENT_SECRET_VALUE="${AZURE_AD_OAUTH_CLIENT_SECRET:-${ACTIVE_DIRECTORY_OAUTH_CLIENT_SECRET}}"
AZURE_AD_DIRECTORY_ID_VALUE="${AZURE_AD_DIRECTORY_ID:-${ACTIVE_DIRECTORY_DIRECTORY_ID}}"
if [ -n "${AZURE_AD_OAUTH_CLIENT_ID_VALUE}" ] && [ -n "${AZURE_AD_OAUTH_CLIENT_SECRET_VALUE}" ] && [ -n "${AZURE_AD_DIRECTORY_ID_VALUE}" ]; then
  EFFECTIVE_AZURE_AD_OAUTH_CLIENT_ID="${AZURE_AD_OAUTH_CLIENT_ID_VALUE}"
  AUTH_OIDC_ENABLED="true"
fi

EFFECTIVE_BOXY_SAML_OAUTH_CLIENT_ID=""
if [ -n "${BOXY_SAML_OAUTH_CLIENT_ID}" ] && [ -n "${BOXY_SAML_OAUTH_CLIENT_SECRET}" ] && [ -n "${BOXY_SAML_URL}" ]; then
  EFFECTIVE_BOXY_SAML_OAUTH_CLIENT_ID="${BOXY_SAML_OAUTH_CLIENT_ID}"
  AUTH_OIDC_ENABLED="true"
fi

# Derive email auth method from SUPERTOKENS_EMAIL_DISABLED and SendGrid status
SUPERTOKENS_EMAIL_DISABLED_VALUE="${SUPERTOKENS_EMAIL_DISABLED:-false}"
EFFECTIVE_AUTHN_EMAIL=""
if [ "${SUPERTOKENS_EMAIL_DISABLED_VALUE}" = "true" ]; then
  EFFECTIVE_AUTHN_EMAIL=""
elif [ "${AGENTA_SENDGRID_ENABLED}" = "true" ]; then
  EFFECTIVE_AUTHN_EMAIL="otp"
else
  EFFECTIVE_AUTHN_EMAIL="password"
fi

AUTH_EMAIL_ENABLED="false"
if [ "${EFFECTIVE_AUTHN_EMAIL}" = "password" ] || [ "${EFFECTIVE_AUTHN_EMAIL}" = "otp" ]; then
  AUTH_EMAIL_ENABLED="true"
fi

cat > "${ENTRYPOINT_DIR}/${AGENTA_LICENSE}/public/__env.js" <<EOF
window.__env = {
  NEXT_PUBLIC_AGENTA_LICENSE: "${AGENTA_LICENSE:-oss}",
  NEXT_PUBLIC_AGENTA_WEB_URL: "${AGENTA_WEB_URL:-http://localhost}",
  NEXT_PUBLIC_AGENTA_API_URL: "${AGENTA_API_URL:-http://localhost/api}",
  NEXT_PUBLIC_POSTHOG_API_KEY: "${POSTHOG_API_KEY}",
  NEXT_PUBLIC_CRISP_WEBSITE_ID: "${CRISP_WEBSITE_ID}",
  NEXT_PUBLIC_AGENTA_AUTHN_EMAIL: "${EFFECTIVE_AUTHN_EMAIL}",
  NEXT_PUBLIC_AGENTA_AUTH_GOOGLE_OAUTH_CLIENT_ID: "${EFFECTIVE_GOOGLE_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_GOOGLE_WORKSPACES_OAUTH_CLIENT_ID: "${EFFECTIVE_GOOGLE_WORKSPACES_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_GITHUB_OAUTH_CLIENT_ID: "${EFFECTIVE_GITHUB_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_FACEBOOK_OAUTH_CLIENT_ID: "${EFFECTIVE_FACEBOOK_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_APPLE_OAUTH_CLIENT_ID: "${EFFECTIVE_APPLE_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_DISCORD_OAUTH_CLIENT_ID: "${EFFECTIVE_DISCORD_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_TWITTER_OAUTH_CLIENT_ID: "${EFFECTIVE_TWITTER_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_GITLAB_OAUTH_CLIENT_ID: "${EFFECTIVE_GITLAB_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_BITBUCKET_OAUTH_CLIENT_ID: "${EFFECTIVE_BITBUCKET_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_LINKEDIN_OAUTH_CLIENT_ID: "${EFFECTIVE_LINKEDIN_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_OKTA_OAUTH_CLIENT_ID: "${EFFECTIVE_OKTA_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_AZURE_AD_OAUTH_CLIENT_ID: "${EFFECTIVE_AZURE_AD_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_BOXY_SAML_OAUTH_CLIENT_ID: "${EFFECTIVE_BOXY_SAML_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_SENDGRID_ENABLED: "${AGENTA_SENDGRID_ENABLED}",
  NEXT_PUBLIC_AGENTA_AUTH_EMAIL_ENABLED: "${AUTH_EMAIL_ENABLED}",
  NEXT_PUBLIC_AGENTA_AUTH_OIDC_ENABLED: "${AUTH_OIDC_ENABLED}",
  NEXT_PUBLIC_AGENTA_TOOLS_ENABLED: "${AGENTA_TOOLS_ENABLED}",
};
EOF

cat "${ENTRYPOINT_DIR}/${AGENTA_LICENSE}/public/__env.js" >&2

exec "$@"
