#!/bin/sh

set -e

if [ "$AGENTA_LICENSE" != "ee" ]; then
  AGENTA_LICENSE="oss"
fi

if [ "$ENTRYPOINT_DIR" != "." ]; then
  ENTRYPOINT_DIR="/app"
fi

# Infer AGENTA_SENDGRID_ENABLED from SENDGRID_API_KEY
if [ -n "$SENDGRID_API_KEY" ]; then
  export AGENTA_SENDGRID_ENABLED="true"
else
  export AGENTA_SENDGRID_ENABLED="false"
fi

mkdir -p "${ENTRYPOINT_DIR}/${AGENTA_LICENSE}/public"

# Derive frontend auth feature flags
# First, check if OIDC providers are configured
AUTH_OIDC_ENABLED="false"
if [ -n "${GOOGLE_OAUTH_CLIENT_ID}" ] && [ -n "${GOOGLE_OAUTH_CLIENT_SECRET}" ]; then
  AUTH_OIDC_ENABLED="true"
fi
if [ -n "${GITHUB_OAUTH_CLIENT_ID}" ] && [ -n "${GITHUB_OAUTH_CLIENT_SECRET}" ]; then
  AUTH_OIDC_ENABLED="true"
fi

# Apply fallback logic: if AGENTA_AUTHN_EMAIL is empty and no OIDC, default to "password"
EFFECTIVE_AUTHN_EMAIL="${AGENTA_AUTHN_EMAIL}"
if [ -z "${EFFECTIVE_AUTHN_EMAIL}" ] && [ "${AUTH_OIDC_ENABLED}" = "false" ]; then
  EFFECTIVE_AUTHN_EMAIL="password"
fi

AUTH_EMAIL_ENABLED="false"
if [ "${EFFECTIVE_AUTHN_EMAIL}" = "password" ] || [ "${EFFECTIVE_AUTHN_EMAIL}" = "otp" ]; then
  AUTH_EMAIL_ENABLED="true"
fi

cat > "${ENTRYPOINT_DIR}/${AGENTA_LICENSE}/public/__env.js" <<EOF
window.__env = {
  NEXT_PUBLIC_AGENTA_LICENSE: "${AGENTA_LICENSE:-oss}",
  NEXT_PUBLIC_AGENTA_API_URL: "${AGENTA_API_URL:-${DOMAIN_NAME:-http://localhost}${AGENTA_PORT:+:$AGENTA_PORT}/api}",
  NEXT_PUBLIC_AGENTA_WEB_URL: "${AGENTA_WEB_URL:-${WEBSITE_DOMAIN_NAME:-${DOMAIN_NAME:-http://localhost}}}",
  NEXT_PUBLIC_POSTHOG_API_KEY: "${POSTHOG_API_KEY}",
  NEXT_PUBLIC_CRISP_WEBSITE_ID: "${CRISP_WEBSITE_ID}",
  NEXT_PUBLIC_AGENTA_AUTHN_EMAIL: "${EFFECTIVE_AUTHN_EMAIL}",
  NEXT_PUBLIC_AGENTA_AUTH_GOOGLE_OAUTH_CLIENT_ID: "${GOOGLE_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_AUTH_GITHUB_OAUTH_CLIENT_ID: "${GITHUB_OAUTH_CLIENT_ID}",
  NEXT_PUBLIC_AGENTA_SENDGRID_ENABLED: "${AGENTA_SENDGRID_ENABLED}",
  NEXT_PUBLIC_AGENTA_AUTH_EMAIL_ENABLED: "${AUTH_EMAIL_ENABLED}",
  NEXT_PUBLIC_AGENTA_AUTH_OIDC_ENABLED: "${AUTH_OIDC_ENABLED}",
};
EOF

cat "${ENTRYPOINT_DIR}/${AGENTA_LICENSE}/public/__env.js" >&2

exec "$@"
