packages:
  - 'oss'
  - 'ee'
  - 'tests'
  - 'packages/*'
allowBuilds:
  '@swc/core': true
  browser-tabs-lock: false
  core-js: true
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
patchedDependencies:
  '@agentaai/nextstepjs@2.1.3-agenta.2': patches/@agentaai__nextstepjs@2.1.3-agenta.2.patch
